// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tictactoe.proto

package tictactoe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mark int32

const (
	Mark_X Mark = 0
	Mark_O Mark = 1
	Mark_E Mark = 2
)

var Mark_name = map[int32]string{
	0: "X",
	1: "O",
	2: "E",
}
var Mark_value = map[string]int32{
	"X": 0,
	"O": 1,
	"E": 2,
}

func (x Mark) String() string {
	return proto.EnumName(Mark_name, int32(x))
}
func (Mark) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{0}
}

type TrxType int32

const (
	TrxType_MOVE TrxType = 0
)

var TrxType_name = map[int32]string{
	0: "MOVE",
}
var TrxType_value = map[string]int32{
	"MOVE": 0,
}

func (x TrxType) String() string {
	return proto.EnumName(TrxType_name, int32(x))
}
func (TrxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{1}
}

type TttContract_Status int32

const (
	TttContract_XTURN TttContract_Status = 0
	TttContract_OTURN TttContract_Status = 1
	TttContract_XWON  TttContract_Status = 2
	TttContract_OWON  TttContract_Status = 3
	TttContract_TIE   TttContract_Status = 4
)

var TttContract_Status_name = map[int32]string{
	0: "XTURN",
	1: "OTURN",
	2: "XWON",
	3: "OWON",
	4: "TIE",
}
var TttContract_Status_value = map[string]int32{
	"XTURN": 0,
	"OTURN": 1,
	"XWON":  2,
	"OWON":  3,
	"TIE":   4,
}

func (x TttContract_Status) String() string {
	return proto.EnumName(TttContract_Status_name, int32(x))
}
func (TttContract_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{0, 0}
}

type TttContract struct {
	Positions            []Mark               `protobuf:"varint,1,rep,packed,name=positions,proto3,enum=tictactoe.Mark" json:"positions,omitempty"`
	Status               TttContract_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=tictactoe.TttContract_Status" json:"status,omitempty"`
	XPlayer              string               `protobuf:"bytes,3,opt,name=x_player,json=xPlayer,proto3" json:"x_player,omitempty"`
	OPlayer              string               `protobuf:"bytes,4,opt,name=o_player,json=oPlayer,proto3" json:"o_player,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TttContract) Reset()         { *m = TttContract{} }
func (m *TttContract) String() string { return proto.CompactTextString(m) }
func (*TttContract) ProtoMessage()    {}
func (*TttContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{0}
}
func (m *TttContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TttContract.Unmarshal(m, b)
}
func (m *TttContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TttContract.Marshal(b, m, deterministic)
}
func (dst *TttContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TttContract.Merge(dst, src)
}
func (m *TttContract) XXX_Size() int {
	return xxx_messageInfo_TttContract.Size(m)
}
func (m *TttContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TttContract.DiscardUnknown(m)
}

var xxx_messageInfo_TttContract proto.InternalMessageInfo

func (m *TttContract) GetPositions() []Mark {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *TttContract) GetStatus() TttContract_Status {
	if m != nil {
		return m.Status
	}
	return TttContract_XTURN
}

func (m *TttContract) GetXPlayer() string {
	if m != nil {
		return m.XPlayer
	}
	return ""
}

func (m *TttContract) GetOPlayer() string {
	if m != nil {
		return m.OPlayer
	}
	return ""
}

func (m *TttContract) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type InitTrxArgs struct {
	Player1Mark          Mark     `protobuf:"varint,1,opt,name=player1_mark,json=player1Mark,proto3,enum=tictactoe.Mark" json:"player1_mark,omitempty"`
	Player2Mark          Mark     `protobuf:"varint,2,opt,name=player2_mark,json=player2Mark,proto3,enum=tictactoe.Mark" json:"player2_mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitTrxArgs) Reset()         { *m = InitTrxArgs{} }
func (m *InitTrxArgs) String() string { return proto.CompactTextString(m) }
func (*InitTrxArgs) ProtoMessage()    {}
func (*InitTrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{1}
}
func (m *InitTrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitTrxArgs.Unmarshal(m, b)
}
func (m *InitTrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitTrxArgs.Marshal(b, m, deterministic)
}
func (dst *InitTrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitTrxArgs.Merge(dst, src)
}
func (m *InitTrxArgs) XXX_Size() int {
	return xxx_messageInfo_InitTrxArgs.Size(m)
}
func (m *InitTrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_InitTrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_InitTrxArgs proto.InternalMessageInfo

func (m *InitTrxArgs) GetPlayer1Mark() Mark {
	if m != nil {
		return m.Player1Mark
	}
	return Mark_X
}

func (m *InitTrxArgs) GetPlayer2Mark() Mark {
	if m != nil {
		return m.Player2Mark
	}
	return Mark_X
}

type TrxArgs struct {
	Type                 TrxType              `protobuf:"varint,1,opt,name=type,proto3,enum=tictactoe.TrxType" json:"type,omitempty"`
	MovePayload          *MoveTrxPayload      `protobuf:"bytes,2,opt,name=movePayload,proto3" json:"movePayload,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrxArgs) Reset()         { *m = TrxArgs{} }
func (m *TrxArgs) String() string { return proto.CompactTextString(m) }
func (*TrxArgs) ProtoMessage()    {}
func (*TrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{2}
}
func (m *TrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxArgs.Unmarshal(m, b)
}
func (m *TrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxArgs.Marshal(b, m, deterministic)
}
func (dst *TrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxArgs.Merge(dst, src)
}
func (m *TrxArgs) XXX_Size() int {
	return xxx_messageInfo_TrxArgs.Size(m)
}
func (m *TrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_TrxArgs proto.InternalMessageInfo

func (m *TrxArgs) GetType() TrxType {
	if m != nil {
		return m.Type
	}
	return TrxType_MOVE
}

func (m *TrxArgs) GetMovePayload() *MoveTrxPayload {
	if m != nil {
		return m.MovePayload
	}
	return nil
}

func (m *TrxArgs) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type MoveTrxPayload struct {
	Position             int32    `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Mark                 Mark     `protobuf:"varint,2,opt,name=mark,proto3,enum=tictactoe.Mark" json:"mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveTrxPayload) Reset()         { *m = MoveTrxPayload{} }
func (m *MoveTrxPayload) String() string { return proto.CompactTextString(m) }
func (*MoveTrxPayload) ProtoMessage()    {}
func (*MoveTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_3e3a0a7e4c073356, []int{3}
}
func (m *MoveTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveTrxPayload.Unmarshal(m, b)
}
func (m *MoveTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveTrxPayload.Marshal(b, m, deterministic)
}
func (dst *MoveTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveTrxPayload.Merge(dst, src)
}
func (m *MoveTrxPayload) XXX_Size() int {
	return xxx_messageInfo_MoveTrxPayload.Size(m)
}
func (m *MoveTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_MoveTrxPayload proto.InternalMessageInfo

func (m *MoveTrxPayload) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *MoveTrxPayload) GetMark() Mark {
	if m != nil {
		return m.Mark
	}
	return Mark_X
}

func init() {
	proto.RegisterType((*TttContract)(nil), "tictactoe.TttContract")
	proto.RegisterType((*InitTrxArgs)(nil), "tictactoe.InitTrxArgs")
	proto.RegisterType((*TrxArgs)(nil), "tictactoe.TrxArgs")
	proto.RegisterType((*MoveTrxPayload)(nil), "tictactoe.MoveTrxPayload")
	proto.RegisterEnum("tictactoe.Mark", Mark_name, Mark_value)
	proto.RegisterEnum("tictactoe.TrxType", TrxType_name, TrxType_value)
	proto.RegisterEnum("tictactoe.TttContract_Status", TttContract_Status_name, TttContract_Status_value)
}

func init() { proto.RegisterFile("tictactoe.proto", fileDescriptor_tictactoe_3e3a0a7e4c073356) }

var fileDescriptor_tictactoe_3e3a0a7e4c073356 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0xaf, 0x93, 0x40,
	0x14, 0x7d, 0x7c, 0xf4, 0x83, 0xcb, 0xcb, 0x7b, 0x64, 0xdc, 0xd0, 0x1a, 0x63, 0x83, 0x89, 0x31,
	0x4d, 0xa4, 0x11, 0xe3, 0xaa, 0x71, 0x61, 0x4c, 0x17, 0x5d, 0xb4, 0xd4, 0x91, 0x6a, 0x77, 0xcd,
	0xb4, 0xc5, 0x86, 0x08, 0x1d, 0x02, 0x83, 0xa1, 0x3f, 0xc8, 0xa5, 0xff, 0xd1, 0x99, 0x01, 0x5a,
	0x4c, 0x4c, 0x37, 0x6f, 0x35, 0xf7, 0x72, 0xce, 0xb9, 0x1f, 0xe7, 0x02, 0x8f, 0x2c, 0xda, 0x33,
	0xb2, 0x67, 0x34, 0x74, 0xd3, 0x8c, 0x32, 0x8a, 0x8c, 0xcb, 0x87, 0xe1, 0xcb, 0x23, 0xa5, 0xc7,
	0x38, 0x9c, 0x48, 0x60, 0x57, 0xfc, 0x98, 0xb0, 0x28, 0x09, 0x73, 0x46, 0x92, 0xb4, 0xe2, 0x3a,
	0xbf, 0x55, 0x30, 0x03, 0xc6, 0x3e, 0xd3, 0x13, 0xcb, 0xb8, 0x04, 0xbd, 0x05, 0x23, 0xa5, 0x79,
	0xc4, 0x22, 0x7a, 0xca, 0x6d, 0x65, 0xa4, 0xbd, 0x79, 0xf0, 0x1e, 0xdd, 0x6b, 0x83, 0x05, 0xc9,
	0x7e, 0xe2, 0x2b, 0x03, 0x7d, 0x80, 0x2e, 0xaf, 0xc6, 0x8a, 0xdc, 0x56, 0x47, 0x0a, 0xe7, 0xbe,
	0x68, 0x71, 0x5b, 0x65, 0xdd, 0xaf, 0x92, 0x84, 0x6b, 0x32, 0x1a, 0x40, 0xbf, 0xdc, 0xa6, 0x31,
	0x39, 0x87, 0x99, 0xad, 0x71, 0xa1, 0x81, 0x7b, 0xe5, 0x4a, 0xa6, 0x02, 0xa2, 0x0d, 0xa4, 0x57,
	0x10, 0xad, 0xa1, 0x8f, 0x70, 0x1f, 0x93, 0x9c, 0x6d, 0x8b, 0xf4, 0x40, 0x58, 0x78, 0xb0, 0x0d,
	0x0e, 0x9b, 0xde, 0xd0, 0xad, 0x76, 0x74, 0x9b, 0x1d, 0xdd, 0xa0, 0xd9, 0x11, 0x9b, 0x82, 0xbf,
	0xae, 0xe8, 0xce, 0x14, 0xba, 0xd5, 0x18, 0xc8, 0x80, 0xce, 0x26, 0x58, 0xe3, 0xa5, 0x75, 0x27,
	0x42, 0x5f, 0x86, 0x0a, 0xea, 0x83, 0xbe, 0xf9, 0xee, 0x2f, 0x2d, 0x55, 0x44, 0xbe, 0x88, 0x34,
	0xd4, 0x03, 0x2d, 0x98, 0xcf, 0x2c, 0xdd, 0x29, 0xc0, 0x9c, 0x9f, 0x22, 0x16, 0x64, 0xe5, 0xa7,
	0xec, 0x98, 0x23, 0x0f, 0xee, 0xab, 0x19, 0xdf, 0x6d, 0x13, 0x6e, 0x09, 0x77, 0x4a, 0xf9, 0x9f,
	0x53, 0x66, 0x4d, 0x12, 0xc9, 0x55, 0xe3, 0x55, 0x1a, 0xf5, 0xa6, 0xc6, 0x13, 0x89, 0xf3, 0x47,
	0x81, 0x5e, 0xd3, 0xf3, 0x35, 0xe8, 0xec, 0x9c, 0x86, 0x75, 0x2f, 0xd4, 0x76, 0x3a, 0x2b, 0x03,
	0x8e, 0x60, 0x89, 0xa3, 0x29, 0x98, 0x09, 0xfd, 0x15, 0xae, 0xc8, 0x39, 0xa6, 0xe4, 0x20, 0xdb,
	0x98, 0xde, 0xa0, 0xdd, 0x86, 0xa3, 0x5c, 0x52, 0x13, 0x70, 0x9b, 0xfd, 0x54, 0x8f, 0xbf, 0xc0,
	0xc3, 0xbf, 0xd5, 0xd1, 0x10, 0xfa, 0xcd, 0xef, 0x22, 0x27, 0xef, 0xe0, 0x4b, 0x8e, 0x5e, 0x81,
	0x7e, 0xcb, 0x09, 0x09, 0x8e, 0x9f, 0x83, 0x2e, 0xed, 0xeb, 0x80, 0xb2, 0xe1, 0x07, 0xe3, 0x8f,
	0xcf, 0x8f, 0xc5, 0x9f, 0x99, 0xa5, 0x8e, 0x9f, 0x49, 0x7b, 0xc4, 0xf2, 0xe2, 0x68, 0x0b, 0xff,
	0xdb, 0xcc, 0xba, 0xdb, 0x75, 0xe5, 0x94, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x45,
	0x88, 0x25, 0x19, 0x03, 0x00, 0x00,
}
