// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tictactoe.proto

package tictactoe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mark int32

const (
	Mark_X Mark = 0
	Mark_O Mark = 1
	Mark_E Mark = 2
)

var Mark_name = map[int32]string{
	0: "X",
	1: "O",
	2: "E",
}
var Mark_value = map[string]int32{
	"X": 0,
	"O": 1,
	"E": 2,
}

func (x Mark) String() string {
	return proto.EnumName(Mark_name, int32(x))
}
func (Mark) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_53a5dd42176b0fae, []int{0}
}

type TttContract_Status int32

const (
	TttContract_XTURN TttContract_Status = 0
	TttContract_OTURN TttContract_Status = 1
	TttContract_XWON  TttContract_Status = 2
	TttContract_OWON  TttContract_Status = 3
	TttContract_TIE   TttContract_Status = 4
)

var TttContract_Status_name = map[int32]string{
	0: "XTURN",
	1: "OTURN",
	2: "XWON",
	3: "OWON",
	4: "TIE",
}
var TttContract_Status_value = map[string]int32{
	"XTURN": 0,
	"OTURN": 1,
	"XWON":  2,
	"OWON":  3,
	"TIE":   4,
}

func (x TttContract_Status) String() string {
	return proto.EnumName(TttContract_Status_name, int32(x))
}
func (TttContract_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_53a5dd42176b0fae, []int{0, 0}
}

type TttContract struct {
	Positions            []Mark               `protobuf:"varint,1,rep,packed,name=positions,proto3,enum=tictactoe.Mark" json:"positions,omitempty"`
	Status               TttContract_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=tictactoe.TttContract_Status" json:"status,omitempty"`
	XPlayer              string               `protobuf:"bytes,3,opt,name=x_player,json=xPlayer,proto3" json:"x_player,omitempty"`
	OPlayer              string               `protobuf:"bytes,4,opt,name=o_player,json=oPlayer,proto3" json:"o_player,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TttContract) Reset()         { *m = TttContract{} }
func (m *TttContract) String() string { return proto.CompactTextString(m) }
func (*TttContract) ProtoMessage()    {}
func (*TttContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_53a5dd42176b0fae, []int{0}
}
func (m *TttContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TttContract.Unmarshal(m, b)
}
func (m *TttContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TttContract.Marshal(b, m, deterministic)
}
func (dst *TttContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TttContract.Merge(dst, src)
}
func (m *TttContract) XXX_Size() int {
	return xxx_messageInfo_TttContract.Size(m)
}
func (m *TttContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TttContract.DiscardUnknown(m)
}

var xxx_messageInfo_TttContract proto.InternalMessageInfo

func (m *TttContract) GetPositions() []Mark {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *TttContract) GetStatus() TttContract_Status {
	if m != nil {
		return m.Status
	}
	return TttContract_XTURN
}

func (m *TttContract) GetXPlayer() string {
	if m != nil {
		return m.XPlayer
	}
	return ""
}

func (m *TttContract) GetOPlayer() string {
	if m != nil {
		return m.OPlayer
	}
	return ""
}

func (m *TttContract) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type InitTrxArgs struct {
	Player1Mark          Mark     `protobuf:"varint,1,opt,name=player1_mark,json=player1Mark,proto3,enum=tictactoe.Mark" json:"player1_mark,omitempty"`
	Player2Mark          Mark     `protobuf:"varint,2,opt,name=player2_mark,json=player2Mark,proto3,enum=tictactoe.Mark" json:"player2_mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitTrxArgs) Reset()         { *m = InitTrxArgs{} }
func (m *InitTrxArgs) String() string { return proto.CompactTextString(m) }
func (*InitTrxArgs) ProtoMessage()    {}
func (*InitTrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_53a5dd42176b0fae, []int{1}
}
func (m *InitTrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitTrxArgs.Unmarshal(m, b)
}
func (m *InitTrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitTrxArgs.Marshal(b, m, deterministic)
}
func (dst *InitTrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitTrxArgs.Merge(dst, src)
}
func (m *InitTrxArgs) XXX_Size() int {
	return xxx_messageInfo_InitTrxArgs.Size(m)
}
func (m *InitTrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_InitTrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_InitTrxArgs proto.InternalMessageInfo

func (m *InitTrxArgs) GetPlayer1Mark() Mark {
	if m != nil {
		return m.Player1Mark
	}
	return Mark_X
}

func (m *InitTrxArgs) GetPlayer2Mark() Mark {
	if m != nil {
		return m.Player2Mark
	}
	return Mark_X
}

type MoveTrxArgs struct {
	Position             int32                `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Mark                 Mark                 `protobuf:"varint,2,opt,name=mark,proto3,enum=tictactoe.Mark" json:"mark,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MoveTrxArgs) Reset()         { *m = MoveTrxArgs{} }
func (m *MoveTrxArgs) String() string { return proto.CompactTextString(m) }
func (*MoveTrxArgs) ProtoMessage()    {}
func (*MoveTrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_tictactoe_53a5dd42176b0fae, []int{2}
}
func (m *MoveTrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveTrxArgs.Unmarshal(m, b)
}
func (m *MoveTrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveTrxArgs.Marshal(b, m, deterministic)
}
func (dst *MoveTrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveTrxArgs.Merge(dst, src)
}
func (m *MoveTrxArgs) XXX_Size() int {
	return xxx_messageInfo_MoveTrxArgs.Size(m)
}
func (m *MoveTrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveTrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_MoveTrxArgs proto.InternalMessageInfo

func (m *MoveTrxArgs) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *MoveTrxArgs) GetMark() Mark {
	if m != nil {
		return m.Mark
	}
	return Mark_X
}

func (m *MoveTrxArgs) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*TttContract)(nil), "tictactoe.TttContract")
	proto.RegisterType((*InitTrxArgs)(nil), "tictactoe.InitTrxArgs")
	proto.RegisterType((*MoveTrxArgs)(nil), "tictactoe.MoveTrxArgs")
	proto.RegisterEnum("tictactoe.Mark", Mark_name, Mark_value)
	proto.RegisterEnum("tictactoe.TttContract_Status", TttContract_Status_name, TttContract_Status_value)
}

func init() { proto.RegisterFile("tictactoe.proto", fileDescriptor_tictactoe_53a5dd42176b0fae) }

var fileDescriptor_tictactoe_53a5dd42176b0fae = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x90, 0xcb, 0x4e, 0xfa, 0x50,
	0x10, 0xc6, 0xff, 0xbd, 0x70, 0xe9, 0x94, 0xfc, 0x69, 0xce, 0xaa, 0x62, 0x8c, 0xa4, 0x6e, 0x8c,
	0x89, 0x25, 0xd6, 0xb8, 0x32, 0x2e, 0x8c, 0x61, 0xc1, 0x02, 0x6a, 0x6a, 0x89, 0xec, 0x48, 0x81,
	0x4a, 0x1a, 0x81, 0xd3, 0xb4, 0x53, 0x83, 0x0f, 0xe1, 0x63, 0xf8, 0x9e, 0x9e, 0x0b, 0xa5, 0x2c,
	0x0c, 0x1b, 0x57, 0x9d, 0xe9, 0xf7, 0xfb, 0x66, 0xce, 0x7c, 0xd0, 0xc6, 0x64, 0x8e, 0xd1, 0x1c,
	0x69, 0xec, 0xa6, 0x19, 0x45, 0x4a, 0x8c, 0xfd, 0x8f, 0xce, 0xf9, 0x92, 0xd2, 0xe5, 0x2a, 0xee,
	0x09, 0x61, 0x56, 0xbc, 0xf5, 0x30, 0x59, 0xc7, 0x39, 0x46, 0xeb, 0x54, 0xb2, 0xce, 0xb7, 0x0a,
	0x66, 0x88, 0xf8, 0x44, 0x37, 0x98, 0x31, 0x0b, 0xb9, 0x06, 0x23, 0xa5, 0x79, 0x82, 0x09, 0xdd,
	0xe4, 0xb6, 0xd2, 0xd5, 0x2e, 0xff, 0x7b, 0x6d, 0xb7, 0x5a, 0x30, 0x8c, 0xb2, 0xf7, 0xa0, 0x22,
	0xc8, 0x1d, 0xd4, 0xd9, 0x34, 0x2c, 0x72, 0x5b, 0xed, 0x2a, 0x8c, 0x3d, 0x3b, 0x60, 0x0f, 0xc6,
	0xba, 0x2f, 0x02, 0x0a, 0x76, 0x30, 0x39, 0x81, 0xe6, 0x76, 0x9a, 0xae, 0xa2, 0xcf, 0x38, 0xb3,
	0x35, 0x66, 0x34, 0x82, 0xc6, 0xf6, 0x59, 0xb4, 0x5c, 0xa2, 0xa5, 0xa4, 0x4b, 0x89, 0xee, 0xa4,
	0x07, 0x68, 0xad, 0xa2, 0x1c, 0xa7, 0x45, 0xba, 0x88, 0x30, 0x5e, 0xd8, 0x06, 0x93, 0x4d, 0xaf,
	0xe3, 0xca, 0x1b, 0xdd, 0xf2, 0x46, 0x37, 0x2c, 0x6f, 0x0c, 0x4c, 0xce, 0x8f, 0x25, 0xee, 0xdc,
	0x43, 0x5d, 0x3e, 0x83, 0x18, 0x50, 0x9b, 0x84, 0xe3, 0x60, 0x64, 0xfd, 0xe3, 0xa5, 0x2f, 0x4a,
	0x85, 0x34, 0x41, 0x9f, 0xbc, 0xfa, 0x23, 0x4b, 0xe5, 0x95, 0xcf, 0x2b, 0x8d, 0x34, 0x40, 0x0b,
	0x07, 0x7d, 0x4b, 0x77, 0x0a, 0x30, 0x07, 0x9b, 0x04, 0xc3, 0x6c, 0xfb, 0x98, 0x2d, 0x73, 0xe2,
	0x41, 0x4b, 0xbe, 0xf1, 0x66, 0xba, 0x66, 0x91, 0xb0, 0xa4, 0x94, 0xdf, 0x92, 0x32, 0x77, 0x10,
	0x6f, 0x2a, 0x8f, 0x27, 0x3d, 0xea, 0x51, 0x8f, 0xc7, 0x1b, 0xe7, 0x4b, 0x01, 0x73, 0x48, 0x3f,
	0xe2, 0x72, 0x6f, 0x07, 0x9a, 0x65, 0xf8, 0x62, 0x67, 0x2d, 0xd8, 0xf7, 0xe4, 0x02, 0xf4, 0x63,
	0x73, 0x85, 0xf8, 0xc7, 0x0c, 0xaf, 0x4e, 0x41, 0x17, 0xb7, 0xd4, 0x40, 0x99, 0xb0, 0xf4, 0xd8,
	0xc7, 0x67, 0xc9, 0xb1, 0x4f, 0xdf, 0x52, 0x67, 0x75, 0xe1, 0xbe, 0xfd, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x02, 0x73, 0x01, 0xe7, 0x91, 0x02, 0x00, 0x00,
}
