// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catan.proto

package catan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Settlement int32

const (
	Settlement_NOSETTLE    Settlement = 0
	Settlement_REDSETTLE   Settlement = 1
	Settlement_GREENSETTLE Settlement = 2
	Settlement_BLUESETTLE  Settlement = 3
)

var Settlement_name = map[int32]string{
	0: "NOSETTLE",
	1: "REDSETTLE",
	2: "GREENSETTLE",
	3: "BLUESETTLE",
}
var Settlement_value = map[string]int32{
	"NOSETTLE":    0,
	"REDSETTLE":   1,
	"GREENSETTLE": 2,
	"BLUESETTLE":  3,
}

func (x Settlement) String() string {
	return proto.EnumName(Settlement_name, int32(x))
}
func (Settlement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{0}
}

type Resource int32

const (
	Resource_HILL     Resource = 0
	Resource_FOREST   Resource = 1
	Resource_MOUNTAIN Resource = 2
	Resource_FIELD    Resource = 3
	Resource_PASTURE  Resource = 4
	Resource_CAMP     Resource = 5
)

var Resource_name = map[int32]string{
	0: "HILL",
	1: "FOREST",
	2: "MOUNTAIN",
	3: "FIELD",
	4: "PASTURE",
	5: "CAMP",
}
var Resource_value = map[string]int32{
	"HILL":     0,
	"FOREST":   1,
	"MOUNTAIN": 2,
	"FIELD":    3,
	"PASTURE":  4,
	"CAMP":     5,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}
func (Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{1}
}

type Road int32

const (
	Road_NOROAD    Road = 0
	Road_REDROAD   Road = 1
	Road_GREENROAD Road = 2
	Road_BLUEROAD  Road = 3
)

var Road_name = map[int32]string{
	0: "NOROAD",
	1: "REDROAD",
	2: "GREENROAD",
	3: "BLUEROAD",
}
var Road_value = map[string]int32{
	"NOROAD":    0,
	"REDROAD":   1,
	"GREENROAD": 2,
	"BLUEROAD":  3,
}

func (x Road) String() string {
	return proto.EnumName(Road_name, int32(x))
}
func (Road) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{2}
}

type IntersectionAttributes struct {
	Settlement           Settlement `protobuf:"varint,1,opt,name=settlement,proto3,enum=catan.Settlement" json:"settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IntersectionAttributes) Reset()         { *m = IntersectionAttributes{} }
func (m *IntersectionAttributes) String() string { return proto.CompactTextString(m) }
func (*IntersectionAttributes) ProtoMessage()    {}
func (*IntersectionAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{0}
}
func (m *IntersectionAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntersectionAttributes.Unmarshal(m, b)
}
func (m *IntersectionAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntersectionAttributes.Marshal(b, m, deterministic)
}
func (dst *IntersectionAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntersectionAttributes.Merge(dst, src)
}
func (m *IntersectionAttributes) XXX_Size() int {
	return xxx_messageInfo_IntersectionAttributes.Size(m)
}
func (m *IntersectionAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_IntersectionAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_IntersectionAttributes proto.InternalMessageInfo

func (m *IntersectionAttributes) GetSettlement() Settlement {
	if m != nil {
		return m.Settlement
	}
	return Settlement_NOSETTLE
}

type Intersection struct {
	Id                   int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncidentEdge         int32                   `protobuf:"varint,2,opt,name=incidentEdge,proto3" json:"incidentEdge,omitempty"`
	Attributes           *IntersectionAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Coordinates          string                  `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Intersection) Reset()         { *m = Intersection{} }
func (m *Intersection) String() string { return proto.CompactTextString(m) }
func (*Intersection) ProtoMessage()    {}
func (*Intersection) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{1}
}
func (m *Intersection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intersection.Unmarshal(m, b)
}
func (m *Intersection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intersection.Marshal(b, m, deterministic)
}
func (dst *Intersection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intersection.Merge(dst, src)
}
func (m *Intersection) XXX_Size() int {
	return xxx_messageInfo_Intersection.Size(m)
}
func (m *Intersection) XXX_DiscardUnknown() {
	xxx_messageInfo_Intersection.DiscardUnknown(m)
}

var xxx_messageInfo_Intersection proto.InternalMessageInfo

func (m *Intersection) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intersection) GetIncidentEdge() int32 {
	if m != nil {
		return m.IncidentEdge
	}
	return 0
}

func (m *Intersection) GetAttributes() *IntersectionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Intersection) GetCoordinates() string {
	if m != nil {
		return m.Coordinates
	}
	return ""
}

type TileAttributes struct {
	Resource             Resource `protobuf:"varint,1,opt,name=resource,proto3,enum=catan.Resource" json:"resource,omitempty"`
	RollNumber           int32    `protobuf:"varint,2,opt,name=rollNumber,proto3" json:"rollNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileAttributes) Reset()         { *m = TileAttributes{} }
func (m *TileAttributes) String() string { return proto.CompactTextString(m) }
func (*TileAttributes) ProtoMessage()    {}
func (*TileAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{2}
}
func (m *TileAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileAttributes.Unmarshal(m, b)
}
func (m *TileAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileAttributes.Marshal(b, m, deterministic)
}
func (dst *TileAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileAttributes.Merge(dst, src)
}
func (m *TileAttributes) XXX_Size() int {
	return xxx_messageInfo_TileAttributes.Size(m)
}
func (m *TileAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_TileAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_TileAttributes proto.InternalMessageInfo

func (m *TileAttributes) GetResource() Resource {
	if m != nil {
		return m.Resource
	}
	return Resource_HILL
}

func (m *TileAttributes) GetRollNumber() int32 {
	if m != nil {
		return m.RollNumber
	}
	return 0
}

type Tile struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OuterComponent       int32           `protobuf:"varint,2,opt,name=outerComponent,proto3" json:"outerComponent,omitempty"`
	Attributes           *TileAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{3}
}
func (m *Tile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tile.Unmarshal(m, b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
}
func (dst *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(dst, src)
}
func (m *Tile) XXX_Size() int {
	return xxx_messageInfo_Tile.Size(m)
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tile) GetOuterComponent() int32 {
	if m != nil {
		return m.OuterComponent
	}
	return 0
}

func (m *Tile) GetAttributes() *TileAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type EdgeAttributes struct {
	Road                 Road     `protobuf:"varint,1,opt,name=road,proto3,enum=catan.Road" json:"road,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeAttributes) Reset()         { *m = EdgeAttributes{} }
func (m *EdgeAttributes) String() string { return proto.CompactTextString(m) }
func (*EdgeAttributes) ProtoMessage()    {}
func (*EdgeAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{4}
}
func (m *EdgeAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeAttributes.Unmarshal(m, b)
}
func (m *EdgeAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeAttributes.Marshal(b, m, deterministic)
}
func (dst *EdgeAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeAttributes.Merge(dst, src)
}
func (m *EdgeAttributes) XXX_Size() int {
	return xxx_messageInfo_EdgeAttributes.Size(m)
}
func (m *EdgeAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeAttributes proto.InternalMessageInfo

func (m *EdgeAttributes) GetRoad() Road {
	if m != nil {
		return m.Road
	}
	return Road_NOROAD
}

type Edge struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               int32           `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Twin                 int32           `protobuf:"varint,3,opt,name=twin,proto3" json:"twin,omitempty"`
	IncidentTile         int32           `protobuf:"varint,4,opt,name=incidentTile,proto3" json:"incidentTile,omitempty"`
	Next                 int32           `protobuf:"varint,5,opt,name=next,proto3" json:"next,omitempty"`
	Prev                 int32           `protobuf:"varint,6,opt,name=prev,proto3" json:"prev,omitempty"`
	Attributes           *EdgeAttributes `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{5}
}
func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (dst *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(dst, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Edge) GetOrigin() int32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Edge) GetTwin() int32 {
	if m != nil {
		return m.Twin
	}
	return 0
}

func (m *Edge) GetIncidentTile() int32 {
	if m != nil {
		return m.IncidentTile
	}
	return 0
}

func (m *Edge) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *Edge) GetPrev() int32 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *Edge) GetAttributes() *EdgeAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type GameBoard struct {
	Intersections        map[int32]*Intersection `protobuf:"bytes,1,rep,name=intersections,proto3" json:"intersections,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tiles                map[int32]*Tile         `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                map[int32]*Edge         `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GameBoard) Reset()         { *m = GameBoard{} }
func (m *GameBoard) String() string { return proto.CompactTextString(m) }
func (*GameBoard) ProtoMessage()    {}
func (*GameBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_catan_a82670a61a6a31ff, []int{6}
}
func (m *GameBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBoard.Unmarshal(m, b)
}
func (m *GameBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBoard.Marshal(b, m, deterministic)
}
func (dst *GameBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBoard.Merge(dst, src)
}
func (m *GameBoard) XXX_Size() int {
	return xxx_messageInfo_GameBoard.Size(m)
}
func (m *GameBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBoard.DiscardUnknown(m)
}

var xxx_messageInfo_GameBoard proto.InternalMessageInfo

func (m *GameBoard) GetIntersections() map[int32]*Intersection {
	if m != nil {
		return m.Intersections
	}
	return nil
}

func (m *GameBoard) GetTiles() map[int32]*Tile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

func (m *GameBoard) GetEdges() map[int32]*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func init() {
	proto.RegisterType((*IntersectionAttributes)(nil), "catan.IntersectionAttributes")
	proto.RegisterType((*Intersection)(nil), "catan.Intersection")
	proto.RegisterType((*TileAttributes)(nil), "catan.TileAttributes")
	proto.RegisterType((*Tile)(nil), "catan.Tile")
	proto.RegisterType((*EdgeAttributes)(nil), "catan.EdgeAttributes")
	proto.RegisterType((*Edge)(nil), "catan.Edge")
	proto.RegisterType((*GameBoard)(nil), "catan.GameBoard")
	proto.RegisterMapType((map[int32]*Edge)(nil), "catan.GameBoard.EdgesEntry")
	proto.RegisterMapType((map[int32]*Intersection)(nil), "catan.GameBoard.IntersectionsEntry")
	proto.RegisterMapType((map[int32]*Tile)(nil), "catan.GameBoard.TilesEntry")
	proto.RegisterEnum("catan.Settlement", Settlement_name, Settlement_value)
	proto.RegisterEnum("catan.Resource", Resource_name, Resource_value)
	proto.RegisterEnum("catan.Road", Road_name, Road_value)
}

func init() { proto.RegisterFile("catan.proto", fileDescriptor_catan_a82670a61a6a31ff) }

var fileDescriptor_catan_a82670a61a6a31ff = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0xd2, 0xb5, 0x37, 0x5b, 0x57, 0x8c, 0x98, 0xaa, 0x21, 0x60, 0x04, 0x09, 0xc1,
	0x90, 0x26, 0x6d, 0x08, 0x09, 0x21, 0x78, 0xe8, 0x36, 0x6f, 0x14, 0xba, 0x76, 0x72, 0xdb, 0x47,
	0x1e, 0xb2, 0xd6, 0x9a, 0x22, 0xda, 0x78, 0x72, 0xdc, 0xc1, 0x3e, 0x07, 0xf1, 0x2d, 0xfc, 0x17,
	0xd7, 0x8e, 0xd7, 0x39, 0x5d, 0x1f, 0x78, 0xf3, 0x3d, 0xb9, 0xe7, 0xf8, 0x1c, 0xdb, 0x37, 0x10,
	0x8d, 0x13, 0x95, 0x64, 0x7b, 0x57, 0x52, 0x28, 0x41, 0x42, 0x53, 0xc4, 0xdf, 0x60, 0xab, 0x93,
	0x29, 0x2e, 0x73, 0x3e, 0x56, 0xa9, 0xc8, 0xda, 0x4a, 0xc9, 0xf4, 0x62, 0xae, 0x78, 0x4e, 0xf6,
	0x01, 0x72, 0xae, 0xd4, 0x94, 0xcf, 0x78, 0xa6, 0x5a, 0xde, 0x8e, 0xf7, 0xba, 0x71, 0xf0, 0x70,
	0xaf, 0x90, 0x18, 0x2c, 0x3e, 0x30, 0xa7, 0x29, 0xfe, 0xe3, 0xc1, 0xba, 0xab, 0x46, 0x1a, 0x50,
	0x49, 0x27, 0x86, 0x1b, 0x32, 0x5c, 0x91, 0x18, 0xd6, 0xd3, 0x6c, 0x9c, 0x4e, 0xb0, 0x99, 0x4e,
	0x2e, 0x79, 0xab, 0x62, 0xbe, 0x94, 0x30, 0xf2, 0x19, 0x20, 0x59, 0xb8, 0x68, 0xf9, 0xd8, 0x11,
	0x1d, 0x3c, 0xb5, 0xfb, 0xae, 0xb6, 0xca, 0x1c, 0x02, 0xd9, 0xc1, 0x98, 0x42, 0xc8, 0x49, 0x9a,
	0x25, 0x9a, 0x1f, 0x22, 0xbf, 0xce, 0x5c, 0x28, 0xfe, 0x0e, 0x8d, 0x61, 0x3a, 0xe5, 0x4e, 0xd4,
	0xb7, 0x50, 0x93, 0x3c, 0x17, 0x73, 0x39, 0xe6, 0x36, 0xe8, 0xa6, 0xdd, 0x90, 0x59, 0x98, 0x2d,
	0x1a, 0xc8, 0x33, 0x00, 0x29, 0xa6, 0xd3, 0xde, 0x7c, 0x76, 0xc1, 0xa5, 0x4d, 0xe0, 0x20, 0xf1,
	0x1c, 0x02, 0x2d, 0x7f, 0x2f, 0xfb, 0x2b, 0x68, 0x08, 0xdc, 0x4d, 0x1e, 0x89, 0xd9, 0x95, 0xc8,
	0xf4, 0x99, 0x16, 0xdc, 0x25, 0x94, 0xbc, 0x5f, 0x91, 0xff, 0xb1, 0xb5, 0x53, 0xf6, 0xed, 0xe6,
	0x8e, 0xf7, 0xa1, 0xa1, 0x8f, 0xcf, 0x49, 0xf5, 0x1c, 0x02, 0x29, 0x92, 0x89, 0x4d, 0x14, 0xdd,
	0x26, 0x42, 0x88, 0x99, 0x0f, 0xf1, 0x5f, 0x0f, 0x02, 0x73, 0xe4, 0xcb, 0x56, 0xb7, 0xa0, 0x2a,
	0x64, 0x7a, 0x99, 0x66, 0xd6, 0xa2, 0xad, 0x08, 0x81, 0x40, 0xfd, 0x44, 0xd4, 0x37, 0xa8, 0x59,
	0xbb, 0x57, 0xaa, 0xdd, 0xb5, 0x82, 0xf2, 0x95, 0x9a, 0xa3, 0x40, 0x5e, 0xc6, 0x7f, 0x29, 0x73,
	0x19, 0xc8, 0xd3, 0x6b, 0x8d, 0x5d, 0x49, 0x7e, 0xdd, 0xaa, 0x16, 0x98, 0x5e, 0x2f, 0x45, 0x5f,
	0x2b, 0x45, 0x2f, 0x87, 0x2b, 0x45, 0xff, 0xed, 0x43, 0xfd, 0x34, 0x99, 0xf1, 0x43, 0x91, 0xc8,
	0x09, 0xe9, 0xc0, 0x46, 0xea, 0x3c, 0x93, 0x1c, 0x73, 0xf9, 0xa8, 0xf3, 0xd2, 0xea, 0x2c, 0x1a,
	0x4b, 0x8f, 0x29, 0xa7, 0x99, 0x92, 0x37, 0xac, 0xcc, 0xc4, 0x11, 0x08, 0x15, 0xfa, 0xcf, 0xf1,
	0x18, 0xb4, 0xc4, 0x93, 0x7b, 0x12, 0x3a, 0x9d, 0xa5, 0x16, 0x9d, 0x9a, 0xc2, 0xd1, 0xa9, 0xbe,
	0xb8, 0xd5, 0x14, 0x9d, 0xe3, 0x96, 0x62, 0x3a, 0xb7, 0x47, 0x40, 0xee, 0x5b, 0x21, 0x4d, 0xf0,
	0x7f, 0xf0, 0x1b, 0x7b, 0x29, 0x7a, 0x49, 0xde, 0x40, 0x78, 0x9d, 0x4c, 0xe7, 0xc5, 0xd4, 0x44,
	0x07, 0x8f, 0x56, 0xcc, 0x04, 0x2b, 0x3a, 0x3e, 0x56, 0x3e, 0x78, 0xdb, 0x14, 0xe0, 0xce, 0xde,
	0x0a, 0xb9, 0x17, 0x65, 0xb9, 0xc8, 0x79, 0x62, 0x4b, 0x32, 0x77, 0x96, 0xff, 0x5f, 0x46, 0x73,
	0x1c, 0x99, 0xdd, 0xaf, 0x00, 0x77, 0x3f, 0x0d, 0xb2, 0x0e, 0xb5, 0x5e, 0x7f, 0x40, 0x87, 0xc3,
	0x2e, 0x6d, 0x3e, 0x20, 0x1b, 0x50, 0x67, 0xf4, 0xd8, 0x96, 0x1e, 0xd9, 0x84, 0xe8, 0x94, 0x51,
	0xda, 0xb3, 0x40, 0x05, 0x9f, 0x27, 0x1c, 0x76, 0x47, 0xd4, 0xd6, 0xfe, 0xee, 0x39, 0xd4, 0x6e,
	0xe7, 0x92, 0xd4, 0x20, 0xf8, 0xd2, 0xe9, 0x76, 0x51, 0x05, 0xa0, 0x7a, 0xd2, 0x67, 0x74, 0x30,
	0x44, 0x09, 0xd4, 0x3f, 0xeb, 0x8f, 0x7a, 0xc3, 0x76, 0xa7, 0x87, 0xfc, 0x3a, 0x84, 0x27, 0x1d,
	0xda, 0x3d, 0x6e, 0xfa, 0x24, 0x82, 0xb5, 0xf3, 0xf6, 0x60, 0x38, 0x62, 0xb4, 0x19, 0x68, 0xee,
	0x51, 0xfb, 0xec, 0xbc, 0x19, 0xee, 0x7e, 0x82, 0x40, 0xcf, 0x85, 0xd6, 0xe8, 0xf5, 0x59, 0xbf,
	0x7d, 0x8c, 0x7a, 0xd8, 0x8a, 0xae, 0x4c, 0xe1, 0x69, 0x8b, 0xc6, 0x93, 0x29, 0x2b, 0x5a, 0x5f,
	0x3b, 0x32, 0x95, 0x7f, 0x51, 0x35, 0x7f, 0xd4, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x04, 0x72, 0x4c, 0x60, 0x05, 0x00, 0x00,
}
