// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alliancecontract.proto

package tfc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllianceState int32

const (
	AllianceState_ACTIVE    AllianceState = 0
	AllianceState_COMPLETED AllianceState = 1
	AllianceState_FAILED    AllianceState = 2
)

var AllianceState_name = map[int32]string{
	0: "ACTIVE",
	1: "COMPLETED",
	2: "FAILED",
}
var AllianceState_value = map[string]int32{
	"ACTIVE":    0,
	"COMPLETED": 1,
	"FAILED":    2,
}

func (x AllianceState) String() string {
	return proto.EnumName(AllianceState_name, int32(x))
}
func (AllianceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_alliancecontract_23883d476eb3f801, []int{0}
}

type AllianceTrxType int32

const (
	AllianceTrxType_INIT   AllianceTrxType = 0
	AllianceTrxType_INVOKE AllianceTrxType = 1
)

var AllianceTrxType_name = map[int32]string{
	0: "INIT",
	1: "INVOKE",
}
var AllianceTrxType_value = map[string]int32{
	"INIT":   0,
	"INVOKE": 1,
}

func (x AllianceTrxType) String() string {
	return proto.EnumName(AllianceTrxType_name, int32(x))
}
func (AllianceTrxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_alliancecontract_23883d476eb3f801, []int{1}
}

type AllianceData struct {
	Terms                []*GameContractTrxArgs `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Lifespan             int32                  `protobuf:"varint,2,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	StartGameState       GameState              `protobuf:"varint,3,opt,name=startGameState,proto3,enum=tfc.GameState" json:"startGameState,omitempty"`
	State                AllianceState          `protobuf:"varint,4,opt,name=state,proto3,enum=tfc.AllianceState" json:"state,omitempty"`
	Allies               []Player               `protobuf:"varint,5,rep,packed,name=allies,proto3,enum=tfc.Player" json:"allies,omitempty"`
	LastUpdated          *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ContractID           uint32                 `protobuf:"varint,10,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AllianceData) Reset()         { *m = AllianceData{} }
func (m *AllianceData) String() string { return proto.CompactTextString(m) }
func (*AllianceData) ProtoMessage()    {}
func (*AllianceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alliancecontract_23883d476eb3f801, []int{0}
}
func (m *AllianceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllianceData.Unmarshal(m, b)
}
func (m *AllianceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllianceData.Marshal(b, m, deterministic)
}
func (dst *AllianceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllianceData.Merge(dst, src)
}
func (m *AllianceData) XXX_Size() int {
	return xxx_messageInfo_AllianceData.Size(m)
}
func (m *AllianceData) XXX_DiscardUnknown() {
	xxx_messageInfo_AllianceData.DiscardUnknown(m)
}

var xxx_messageInfo_AllianceData proto.InternalMessageInfo

func (m *AllianceData) GetTerms() []*GameContractTrxArgs {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *AllianceData) GetLifespan() int32 {
	if m != nil {
		return m.Lifespan
	}
	return 0
}

func (m *AllianceData) GetStartGameState() GameState {
	if m != nil {
		return m.StartGameState
	}
	return GameState_JOINING
}

func (m *AllianceData) GetState() AllianceState {
	if m != nil {
		return m.State
	}
	return AllianceState_ACTIVE
}

func (m *AllianceData) GetAllies() []Player {
	if m != nil {
		return m.Allies
	}
	return nil
}

func (m *AllianceData) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *AllianceData) GetContractID() uint32 {
	if m != nil {
		return m.ContractID
	}
	return 0
}

type AllianceTrxArgs struct {
	Type                 AllianceTrxType      `protobuf:"varint,1,opt,name=type,proto3,enum=tfc.AllianceTrxType" json:"type,omitempty"`
	InitPayload          *AllianceData        `protobuf:"bytes,2,opt,name=initPayload,proto3" json:"initPayload,omitempty"`
	InvokePayload        *TrxCompletedArgs    `protobuf:"bytes,3,opt,name=invokePayload,proto3" json:"invokePayload,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AllianceTrxArgs) Reset()         { *m = AllianceTrxArgs{} }
func (m *AllianceTrxArgs) String() string { return proto.CompactTextString(m) }
func (*AllianceTrxArgs) ProtoMessage()    {}
func (*AllianceTrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_alliancecontract_23883d476eb3f801, []int{1}
}
func (m *AllianceTrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllianceTrxArgs.Unmarshal(m, b)
}
func (m *AllianceTrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllianceTrxArgs.Marshal(b, m, deterministic)
}
func (dst *AllianceTrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllianceTrxArgs.Merge(dst, src)
}
func (m *AllianceTrxArgs) XXX_Size() int {
	return xxx_messageInfo_AllianceTrxArgs.Size(m)
}
func (m *AllianceTrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AllianceTrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AllianceTrxArgs proto.InternalMessageInfo

func (m *AllianceTrxArgs) GetType() AllianceTrxType {
	if m != nil {
		return m.Type
	}
	return AllianceTrxType_INIT
}

func (m *AllianceTrxArgs) GetInitPayload() *AllianceData {
	if m != nil {
		return m.InitPayload
	}
	return nil
}

func (m *AllianceTrxArgs) GetInvokePayload() *TrxCompletedArgs {
	if m != nil {
		return m.InvokePayload
	}
	return nil
}

func (m *AllianceTrxArgs) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*AllianceData)(nil), "tfc.AllianceData")
	proto.RegisterType((*AllianceTrxArgs)(nil), "tfc.AllianceTrxArgs")
	proto.RegisterEnum("tfc.AllianceState", AllianceState_name, AllianceState_value)
	proto.RegisterEnum("tfc.AllianceTrxType", AllianceTrxType_name, AllianceTrxType_value)
}

func init() {
	proto.RegisterFile("alliancecontract.proto", fileDescriptor_alliancecontract_23883d476eb3f801)
}

var fileDescriptor_alliancecontract_23883d476eb3f801 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x91, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0x7f, 0x69, 0x7b, 0x59, 0x43, 0xb1, 0x00, 0x45, 0x39, 0xc0, 0x34, 0x0e, 0x54,
	0x3b, 0x64, 0x52, 0x26, 0xed, 0x82, 0x38, 0x54, 0x6d, 0x41, 0x11, 0x63, 0xab, 0x4c, 0xd8, 0x15,
	0xb9, 0xad, 0x5b, 0x45, 0x38, 0x71, 0x64, 0x7b, 0x13, 0xfd, 0xef, 0xf8, 0x83, 0xf8, 0x23, 0x78,
	0x76, 0x92, 0x69, 0xe1, 0xca, 0x2d, 0xcf, 0xfe, 0x7c, 0x5f, 0x9e, 0x3f, 0x0f, 0x5e, 0x33, 0x21,
	0x72, 0x56, 0x6e, 0xf8, 0x46, 0x96, 0x46, 0xb1, 0x8d, 0x89, 0x2b, 0x25, 0x8d, 0x24, 0x7d, 0xb3,
	0xdb, 0x44, 0x6f, 0xf7, 0x52, 0xee, 0x05, 0xbf, 0x70, 0x47, 0xeb, 0xfb, 0xdd, 0x85, 0xc9, 0x0b,
	0xae, 0x0d, 0x2b, 0xaa, 0x9a, 0x8a, 0x82, 0x3d, 0x2b, 0xf8, 0x96, 0x19, 0xd6, 0xd4, 0xc4, 0xd6,
	0xdd, 0x4e, 0x51, 0x20, 0xd7, 0x9a, 0xab, 0x07, 0xae, 0xea, 0xfa, 0xec, 0x77, 0x0f, 0x4e, 0x66,
	0xcd, 0x4f, 0x17, 0x18, 0x25, 0x31, 0x0c, 0x0d, 0x57, 0x85, 0x0e, 0xbd, 0xd3, 0xfe, 0xd4, 0x4f,
	0xc2, 0x18, 0x7f, 0x1d, 0x7f, 0xc6, 0x46, 0xf3, 0xa6, 0x51, 0xa6, 0x7e, 0xcd, 0xd4, 0x5e, 0xd3,
	0x1a, 0x23, 0x11, 0x1c, 0x89, 0x7c, 0xc7, 0x75, 0xc5, 0xca, 0xb0, 0x77, 0xea, 0x4d, 0x87, 0xf4,
	0xb1, 0x26, 0x57, 0x10, 0xe0, 0x7c, 0xca, 0xd8, 0xf8, 0x37, 0xc3, 0x0c, 0x0f, 0xfb, 0x48, 0x04,
	0x49, 0xf0, 0xd8, 0xd4, 0x9d, 0xd2, 0x7f, 0x28, 0x32, 0x85, 0xa1, 0x76, 0xf8, 0xc0, 0xe1, 0xc4,
	0xe1, 0xed, 0x94, 0x75, 0xa4, 0x06, 0xc8, 0x3b, 0x18, 0x59, 0x65, 0x5c, 0x87, 0x43, 0x1c, 0x37,
	0x48, 0x7c, 0x87, 0xae, 0x04, 0x3b, 0x70, 0x45, 0x9b, 0x2b, 0xf2, 0x11, 0x4e, 0x04, 0xd3, 0xe6,
	0xc7, 0x7d, 0x85, 0x72, 0xf8, 0x36, 0x3c, 0xc6, 0xae, 0x7e, 0x12, 0xc5, 0xb5, 0xcf, 0xb8, 0xf5,
	0x19, 0x67, 0xad, 0x4f, 0xea, 0x5b, 0xfe, 0x7b, 0x8d, 0x93, 0x37, 0x00, 0xad, 0xc4, 0x74, 0x11,
	0x02, 0x86, 0xc7, 0xf4, 0xc9, 0xc9, 0xd9, 0x1f, 0x0f, 0x9e, 0xb7, 0xc3, 0x35, 0x72, 0xf0, 0x05,
	0x03, 0x73, 0xa8, 0x38, 0x4a, 0xb4, 0x0f, 0x78, 0xd9, 0x79, 0x00, 0x32, 0x19, 0xde, 0x51, 0x47,
	0x90, 0x4b, 0xf0, 0xf3, 0x32, 0x37, 0x2b, 0x76, 0x10, 0x92, 0x6d, 0x9d, 0x42, 0x3f, 0x79, 0xd1,
	0x09, 0xd8, 0xbd, 0xd0, 0xa7, 0x14, 0xf9, 0x00, 0xe3, 0xbc, 0x7c, 0x90, 0x3f, 0x79, 0x1b, 0xeb,
	0xbb, 0xd8, 0x2b, 0x17, 0xc3, 0xfe, 0x73, 0x59, 0x54, 0x82, 0xe3, 0xf0, 0x6e, 0x53, 0x5d, 0xf6,
	0x3f, 0x75, 0x9c, 0x5f, 0xc1, 0xb8, 0xb3, 0x0a, 0x02, 0x30, 0x9a, 0xcd, 0xb3, 0xf4, 0x6e, 0x39,
	0x79, 0x46, 0xc6, 0x70, 0x3c, 0xbf, 0xfd, 0xba, 0xba, 0x5e, 0x66, 0xcb, 0xc5, 0xc4, 0xb3, 0x57,
	0x9f, 0x66, 0xe9, 0x35, 0x7e, 0xf7, 0xce, 0xdf, 0x77, 0x2c, 0x59, 0x03, 0xe4, 0x08, 0x06, 0xe9,
	0x4d, 0x9a, 0x61, 0x0e, 0xc1, 0xf4, 0xe6, 0xee, 0xf6, 0xcb, 0x72, 0xe2, 0xad, 0x47, 0x6e, 0x82,
	0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x0c, 0x67, 0x2b, 0x0d, 0x03, 0x00, 0x00,
}
