// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battlecontract.proto

package tfc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BattleAction int32

const (
	BattleAction_ATTACK  BattleAction = 0
	BattleAction_DEFFEND BattleAction = 1
)

var BattleAction_name = map[int32]string{
	0: "ATTACK",
	1: "DEFFEND",
}
var BattleAction_value = map[string]int32{
	"ATTACK":  0,
	"DEFFEND": 1,
}

func (x BattleAction) String() string {
	return proto.EnumName(BattleAction_name, int32(x))
}
func (BattleAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_battlecontract_b8c26e25dba73bc6, []int{0}
}

type BattleTrxPayload struct {
	Action               BattleAction         `protobuf:"varint,1,opt,name=action,proto3,enum=tfc.BattleAction" json:"action,omitempty"`
	NOfUnits             int32                `protobuf:"varint,2,opt,name=nOfUnits,proto3" json:"nOfUnits,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BattleTrxPayload) Reset()         { *m = BattleTrxPayload{} }
func (m *BattleTrxPayload) String() string { return proto.CompactTextString(m) }
func (*BattleTrxPayload) ProtoMessage()    {}
func (*BattleTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_battlecontract_b8c26e25dba73bc6, []int{0}
}
func (m *BattleTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleTrxPayload.Unmarshal(m, b)
}
func (m *BattleTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleTrxPayload.Marshal(b, m, deterministic)
}
func (dst *BattleTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleTrxPayload.Merge(dst, src)
}
func (m *BattleTrxPayload) XXX_Size() int {
	return xxx_messageInfo_BattleTrxPayload.Size(m)
}
func (m *BattleTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BattleTrxPayload proto.InternalMessageInfo

func (m *BattleTrxPayload) GetAction() BattleAction {
	if m != nil {
		return m.Action
	}
	return BattleAction_ATTACK
}

func (m *BattleTrxPayload) GetNOfUnits() int32 {
	if m != nil {
		return m.NOfUnits
	}
	return 0
}

func (m *BattleTrxPayload) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*BattleTrxPayload)(nil), "tfc.BattleTrxPayload")
	proto.RegisterEnum("tfc.BattleAction", BattleAction_name, BattleAction_value)
}

func init() {
	proto.RegisterFile("battlecontract.proto", fileDescriptor_battlecontract_b8c26e25dba73bc6)
}

var fileDescriptor_battlecontract_b8c26e25dba73bc6 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0x4d, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2e, 0x49, 0x4b, 0x96, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b,
	0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x54, 0x29,
	0xcd, 0x60, 0xe4, 0x12, 0x70, 0x02, 0x6b, 0x0f, 0x29, 0xaa, 0x08, 0x48, 0xac, 0xcc, 0xc9, 0x4f,
	0x4c, 0x11, 0xd2, 0xe4, 0x62, 0x03, 0x9a, 0x93, 0x99, 0x9f, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x67, 0x24, 0xa8, 0x07, 0x34, 0x4b, 0x0f, 0xa2, 0xcc, 0x11, 0x2c, 0x11, 0x04, 0x55, 0x20, 0x24,
	0xc5, 0xc5, 0x91, 0xe7, 0x9f, 0x16, 0x9a, 0x97, 0x59, 0x52, 0x2c, 0xc1, 0x04, 0x54, 0xcc, 0x1a,
	0x04, 0xe7, 0x0b, 0xd9, 0x72, 0xf1, 0xe4, 0x24, 0x16, 0x97, 0xc4, 0x97, 0x16, 0xa4, 0x24, 0x96,
	0xa4, 0xa6, 0x48, 0x70, 0x02, 0xe5, 0xb9, 0x8d, 0xa4, 0xf4, 0x20, 0x6e, 0xd2, 0x83, 0xb9, 0x49,
	0x2f, 0x04, 0xe6, 0xa6, 0x20, 0x6e, 0x90, 0xfa, 0x50, 0x88, 0x72, 0x2d, 0x75, 0x2e, 0x1e, 0x64,
	0x2b, 0x85, 0xb8, 0xb8, 0xd8, 0x1c, 0x43, 0x42, 0x1c, 0x9d, 0xbd, 0x05, 0x18, 0x84, 0xb8, 0xb9,
	0xd8, 0x5d, 0x5c, 0xdd, 0xdc, 0x5c, 0xfd, 0x5c, 0x04, 0x18, 0x93, 0xd8, 0xc0, 0x26, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xf3, 0xb3, 0x62, 0x08, 0x01, 0x00, 0x00,
}
