/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gamedata_pb = require('./gamedata_pb.js');
var battlecontract_pb = require('./battlecontract_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.exportSymbol('proto.tfc.BuildRoadPayload', null, global);
goog.exportSymbol('proto.tfc.BuildSettlePayload', null, global);
goog.exportSymbol('proto.tfc.BuildTrxPayload', null, global);
goog.exportSymbol('proto.tfc.BuildType', null, global);
goog.exportSymbol('proto.tfc.GameContractInitArgs', null, global);
goog.exportSymbol('proto.tfc.GameContractTrxArgs', null, global);
goog.exportSymbol('proto.tfc.GameTrxType', null, global);
goog.exportSymbol('proto.tfc.JoinTrxPayload', null, global);
goog.exportSymbol('proto.tfc.TradeTrxPayload', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.JoinTrxPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.JoinTrxPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.JoinTrxPayload.displayName = 'proto.tfc.JoinTrxPayload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.JoinTrxPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.JoinTrxPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.JoinTrxPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.JoinTrxPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    player: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.JoinTrxPayload}
 */
proto.tfc.JoinTrxPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.JoinTrxPayload;
  return proto.tfc.JoinTrxPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.JoinTrxPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.JoinTrxPayload}
 */
proto.tfc.JoinTrxPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tfc.Player} */ (reader.readEnum());
      msg.setPlayer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.JoinTrxPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.JoinTrxPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.JoinTrxPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.JoinTrxPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayer();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional Player player = 1;
 * @return {!proto.tfc.Player}
 */
proto.tfc.JoinTrxPayload.prototype.getPlayer = function() {
  return /** @type {!proto.tfc.Player} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.tfc.Player} value */
proto.tfc.JoinTrxPayload.prototype.setPlayer = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.TradeTrxPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.TradeTrxPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.TradeTrxPayload.displayName = 'proto.tfc.TradeTrxPayload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.TradeTrxPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.TradeTrxPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.TradeTrxPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.TradeTrxPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dest: jspb.Message.getFieldWithDefault(msg, 2, 0),
    resource: jspb.Message.getFieldWithDefault(msg, 3, 0),
    amount: jspb.Message.getFieldWithDefault(msg, 4, 0),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.TradeTrxPayload}
 */
proto.tfc.TradeTrxPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.TradeTrxPayload;
  return proto.tfc.TradeTrxPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.TradeTrxPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.TradeTrxPayload}
 */
proto.tfc.TradeTrxPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tfc.Player} */ (reader.readEnum());
      msg.setSource(value);
      break;
    case 2:
      var value = /** @type {!proto.tfc.Player} */ (reader.readEnum());
      msg.setDest(value);
      break;
    case 3:
      var value = /** @type {!proto.tfc.Resource} */ (reader.readEnum());
      msg.setResource(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAmount(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.TradeTrxPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.TradeTrxPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.TradeTrxPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.TradeTrxPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getDest();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getResource();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional Player source = 1;
 * @return {!proto.tfc.Player}
 */
proto.tfc.TradeTrxPayload.prototype.getSource = function() {
  return /** @type {!proto.tfc.Player} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.tfc.Player} value */
proto.tfc.TradeTrxPayload.prototype.setSource = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Player dest = 2;
 * @return {!proto.tfc.Player}
 */
proto.tfc.TradeTrxPayload.prototype.getDest = function() {
  return /** @type {!proto.tfc.Player} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.tfc.Player} value */
proto.tfc.TradeTrxPayload.prototype.setDest = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Resource resource = 3;
 * @return {!proto.tfc.Resource}
 */
proto.tfc.TradeTrxPayload.prototype.getResource = function() {
  return /** @type {!proto.tfc.Resource} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.tfc.Resource} value */
proto.tfc.TradeTrxPayload.prototype.setResource = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int32 amount = 4;
 * @return {number}
 */
proto.tfc.TradeTrxPayload.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.tfc.TradeTrxPayload.prototype.setAmount = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.TradeTrxPayload.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.TradeTrxPayload.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.TradeTrxPayload.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.TradeTrxPayload.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.BuildRoadPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.BuildRoadPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.BuildRoadPayload.displayName = 'proto.tfc.BuildRoadPayload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.BuildRoadPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.BuildRoadPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.BuildRoadPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildRoadPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    edgeid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    player: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.BuildRoadPayload}
 */
proto.tfc.BuildRoadPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.BuildRoadPayload;
  return proto.tfc.BuildRoadPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.BuildRoadPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.BuildRoadPayload}
 */
proto.tfc.BuildRoadPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEdgeid(value);
      break;
    case 2:
      var value = /** @type {!proto.tfc.Player} */ (reader.readEnum());
      msg.setPlayer(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.BuildRoadPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.BuildRoadPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.BuildRoadPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildRoadPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEdgeid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 edgeID = 1;
 * @return {number}
 */
proto.tfc.BuildRoadPayload.prototype.getEdgeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tfc.BuildRoadPayload.prototype.setEdgeid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Player player = 2;
 * @return {!proto.tfc.Player}
 */
proto.tfc.BuildRoadPayload.prototype.getPlayer = function() {
  return /** @type {!proto.tfc.Player} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.tfc.Player} value */
proto.tfc.BuildRoadPayload.prototype.setPlayer = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.BuildRoadPayload.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.BuildRoadPayload.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.BuildRoadPayload.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.BuildRoadPayload.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.BuildSettlePayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.BuildSettlePayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.BuildSettlePayload.displayName = 'proto.tfc.BuildSettlePayload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.BuildSettlePayload.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.BuildSettlePayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.BuildSettlePayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildSettlePayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    settleid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    player: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.BuildSettlePayload}
 */
proto.tfc.BuildSettlePayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.BuildSettlePayload;
  return proto.tfc.BuildSettlePayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.BuildSettlePayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.BuildSettlePayload}
 */
proto.tfc.BuildSettlePayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSettleid(value);
      break;
    case 2:
      var value = /** @type {!proto.tfc.Player} */ (reader.readEnum());
      msg.setPlayer(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.BuildSettlePayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.BuildSettlePayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.BuildSettlePayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildSettlePayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSettleid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 settleID = 1;
 * @return {number}
 */
proto.tfc.BuildSettlePayload.prototype.getSettleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tfc.BuildSettlePayload.prototype.setSettleid = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Player player = 2;
 * @return {!proto.tfc.Player}
 */
proto.tfc.BuildSettlePayload.prototype.getPlayer = function() {
  return /** @type {!proto.tfc.Player} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.tfc.Player} value */
proto.tfc.BuildSettlePayload.prototype.setPlayer = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.BuildSettlePayload.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.BuildSettlePayload.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.BuildSettlePayload.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.BuildSettlePayload.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.BuildTrxPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.BuildTrxPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.BuildTrxPayload.displayName = 'proto.tfc.BuildTrxPayload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.BuildTrxPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.BuildTrxPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.BuildTrxPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildTrxPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    buildroadpayload: (f = msg.getBuildroadpayload()) && proto.tfc.BuildRoadPayload.toObject(includeInstance, f),
    buildsettlepayload: (f = msg.getBuildsettlepayload()) && proto.tfc.BuildSettlePayload.toObject(includeInstance, f),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.BuildTrxPayload}
 */
proto.tfc.BuildTrxPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.BuildTrxPayload;
  return proto.tfc.BuildTrxPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.BuildTrxPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.BuildTrxPayload}
 */
proto.tfc.BuildTrxPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tfc.BuildType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.tfc.BuildRoadPayload;
      reader.readMessage(value,proto.tfc.BuildRoadPayload.deserializeBinaryFromReader);
      msg.setBuildroadpayload(value);
      break;
    case 3:
      var value = new proto.tfc.BuildSettlePayload;
      reader.readMessage(value,proto.tfc.BuildSettlePayload.deserializeBinaryFromReader);
      msg.setBuildsettlepayload(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.BuildTrxPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.BuildTrxPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.BuildTrxPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.BuildTrxPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBuildroadpayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.tfc.BuildRoadPayload.serializeBinaryToWriter
    );
  }
  f = message.getBuildsettlepayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.tfc.BuildSettlePayload.serializeBinaryToWriter
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional BuildType type = 1;
 * @return {!proto.tfc.BuildType}
 */
proto.tfc.BuildTrxPayload.prototype.getType = function() {
  return /** @type {!proto.tfc.BuildType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.tfc.BuildType} value */
proto.tfc.BuildTrxPayload.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional BuildRoadPayload buildRoadPayload = 2;
 * @return {?proto.tfc.BuildRoadPayload}
 */
proto.tfc.BuildTrxPayload.prototype.getBuildroadpayload = function() {
  return /** @type{?proto.tfc.BuildRoadPayload} */ (
    jspb.Message.getWrapperField(this, proto.tfc.BuildRoadPayload, 2));
};


/** @param {?proto.tfc.BuildRoadPayload|undefined} value */
proto.tfc.BuildTrxPayload.prototype.setBuildroadpayload = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tfc.BuildTrxPayload.prototype.clearBuildroadpayload = function() {
  this.setBuildroadpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.BuildTrxPayload.prototype.hasBuildroadpayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BuildSettlePayload buildSettlePayload = 3;
 * @return {?proto.tfc.BuildSettlePayload}
 */
proto.tfc.BuildTrxPayload.prototype.getBuildsettlepayload = function() {
  return /** @type{?proto.tfc.BuildSettlePayload} */ (
    jspb.Message.getWrapperField(this, proto.tfc.BuildSettlePayload, 3));
};


/** @param {?proto.tfc.BuildSettlePayload|undefined} value */
proto.tfc.BuildTrxPayload.prototype.setBuildsettlepayload = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.tfc.BuildTrxPayload.prototype.clearBuildsettlepayload = function() {
  this.setBuildsettlepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.BuildTrxPayload.prototype.hasBuildsettlepayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.BuildTrxPayload.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.BuildTrxPayload.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.BuildTrxPayload.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.BuildTrxPayload.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.GameContractTrxArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.GameContractTrxArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.GameContractTrxArgs.displayName = 'proto.tfc.GameContractTrxArgs';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.GameContractTrxArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.GameContractTrxArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.GameContractTrxArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.GameContractTrxArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tradetrxpayload: (f = msg.getTradetrxpayload()) && proto.tfc.TradeTrxPayload.toObject(includeInstance, f),
    buildtrxpayload: (f = msg.getBuildtrxpayload()) && proto.tfc.BuildTrxPayload.toObject(includeInstance, f),
    battletrxpayload: (f = msg.getBattletrxpayload()) && battlecontract_pb.BattleTrxPayload.toObject(includeInstance, f),
    jointrxpayload: (f = msg.getJointrxpayload()) && proto.tfc.JoinTrxPayload.toObject(includeInstance, f),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.GameContractTrxArgs}
 */
proto.tfc.GameContractTrxArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.GameContractTrxArgs;
  return proto.tfc.GameContractTrxArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.GameContractTrxArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.GameContractTrxArgs}
 */
proto.tfc.GameContractTrxArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tfc.GameTrxType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.tfc.TradeTrxPayload;
      reader.readMessage(value,proto.tfc.TradeTrxPayload.deserializeBinaryFromReader);
      msg.setTradetrxpayload(value);
      break;
    case 3:
      var value = new proto.tfc.BuildTrxPayload;
      reader.readMessage(value,proto.tfc.BuildTrxPayload.deserializeBinaryFromReader);
      msg.setBuildtrxpayload(value);
      break;
    case 4:
      var value = new battlecontract_pb.BattleTrxPayload;
      reader.readMessage(value,battlecontract_pb.BattleTrxPayload.deserializeBinaryFromReader);
      msg.setBattletrxpayload(value);
      break;
    case 5:
      var value = new proto.tfc.JoinTrxPayload;
      reader.readMessage(value,proto.tfc.JoinTrxPayload.deserializeBinaryFromReader);
      msg.setJointrxpayload(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.GameContractTrxArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.GameContractTrxArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.GameContractTrxArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.GameContractTrxArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTradetrxpayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.tfc.TradeTrxPayload.serializeBinaryToWriter
    );
  }
  f = message.getBuildtrxpayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.tfc.BuildTrxPayload.serializeBinaryToWriter
    );
  }
  f = message.getBattletrxpayload();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      battlecontract_pb.BattleTrxPayload.serializeBinaryToWriter
    );
  }
  f = message.getJointrxpayload();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.tfc.JoinTrxPayload.serializeBinaryToWriter
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional GameTrxType type = 1;
 * @return {!proto.tfc.GameTrxType}
 */
proto.tfc.GameContractTrxArgs.prototype.getType = function() {
  return /** @type {!proto.tfc.GameTrxType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.tfc.GameTrxType} value */
proto.tfc.GameContractTrxArgs.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TradeTrxPayload tradeTrxPayload = 2;
 * @return {?proto.tfc.TradeTrxPayload}
 */
proto.tfc.GameContractTrxArgs.prototype.getTradetrxpayload = function() {
  return /** @type{?proto.tfc.TradeTrxPayload} */ (
    jspb.Message.getWrapperField(this, proto.tfc.TradeTrxPayload, 2));
};


/** @param {?proto.tfc.TradeTrxPayload|undefined} value */
proto.tfc.GameContractTrxArgs.prototype.setTradetrxpayload = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tfc.GameContractTrxArgs.prototype.clearTradetrxpayload = function() {
  this.setTradetrxpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractTrxArgs.prototype.hasTradetrxpayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BuildTrxPayload buildTrxPayload = 3;
 * @return {?proto.tfc.BuildTrxPayload}
 */
proto.tfc.GameContractTrxArgs.prototype.getBuildtrxpayload = function() {
  return /** @type{?proto.tfc.BuildTrxPayload} */ (
    jspb.Message.getWrapperField(this, proto.tfc.BuildTrxPayload, 3));
};


/** @param {?proto.tfc.BuildTrxPayload|undefined} value */
proto.tfc.GameContractTrxArgs.prototype.setBuildtrxpayload = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.tfc.GameContractTrxArgs.prototype.clearBuildtrxpayload = function() {
  this.setBuildtrxpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractTrxArgs.prototype.hasBuildtrxpayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional BattleTrxPayload battleTrxPayload = 4;
 * @return {?proto.tfc.BattleTrxPayload}
 */
proto.tfc.GameContractTrxArgs.prototype.getBattletrxpayload = function() {
  return /** @type{?proto.tfc.BattleTrxPayload} */ (
    jspb.Message.getWrapperField(this, battlecontract_pb.BattleTrxPayload, 4));
};


/** @param {?proto.tfc.BattleTrxPayload|undefined} value */
proto.tfc.GameContractTrxArgs.prototype.setBattletrxpayload = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.tfc.GameContractTrxArgs.prototype.clearBattletrxpayload = function() {
  this.setBattletrxpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractTrxArgs.prototype.hasBattletrxpayload = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional JoinTrxPayload joinTrxPayload = 5;
 * @return {?proto.tfc.JoinTrxPayload}
 */
proto.tfc.GameContractTrxArgs.prototype.getJointrxpayload = function() {
  return /** @type{?proto.tfc.JoinTrxPayload} */ (
    jspb.Message.getWrapperField(this, proto.tfc.JoinTrxPayload, 5));
};


/** @param {?proto.tfc.JoinTrxPayload|undefined} value */
proto.tfc.GameContractTrxArgs.prototype.setJointrxpayload = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.tfc.GameContractTrxArgs.prototype.clearJointrxpayload = function() {
  this.setJointrxpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractTrxArgs.prototype.hasJointrxpayload = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.GameContractTrxArgs.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.GameContractTrxArgs.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.GameContractTrxArgs.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractTrxArgs.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tfc.GameContractInitArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tfc.GameContractInitArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tfc.GameContractInitArgs.displayName = 'proto.tfc.GameContractInitArgs';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tfc.GameContractInitArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.tfc.GameContractInitArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tfc.GameContractInitArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.GameContractInitArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: msg.getUuid_asB64(),
    lastUpdated: (f = msg.getLastUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tfc.GameContractInitArgs}
 */
proto.tfc.GameContractInitArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tfc.GameContractInitArgs;
  return proto.tfc.GameContractInitArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tfc.GameContractInitArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tfc.GameContractInitArgs}
 */
proto.tfc.GameContractInitArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setUuid(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tfc.GameContractInitArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tfc.GameContractInitArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tfc.GameContractInitArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tfc.GameContractInitArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes uuid = 1;
 * @return {!(string|Uint8Array)}
 */
proto.tfc.GameContractInitArgs.prototype.getUuid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes uuid = 1;
 * This is a type-conversion wrapper around `getUuid()`
 * @return {string}
 */
proto.tfc.GameContractInitArgs.prototype.getUuid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getUuid()));
};


/**
 * optional bytes uuid = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getUuid()`
 * @return {!Uint8Array}
 */
proto.tfc.GameContractInitArgs.prototype.getUuid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getUuid()));
};


/** @param {!(string|Uint8Array)} value */
proto.tfc.GameContractInitArgs.prototype.setUuid = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp last_updated = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tfc.GameContractInitArgs.prototype.getLastUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.tfc.GameContractInitArgs.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.tfc.GameContractInitArgs.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tfc.GameContractInitArgs.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * @enum {number}
 */
proto.tfc.BuildType = {
  ROAD: 0,
  SETTLE: 1
};

/**
 * @enum {number}
 */
proto.tfc.GameTrxType = {
  JOIN: 0,
  NEXT: 1,
  ROLL: 2,
  TRADE: 3,
  DEV: 4,
  BATTLE: 5,
  REGISTERL: 6
};

goog.object.extend(exports, proto.tfc);
