// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedata.proto

package tfc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Settlement int32

const (
	Settlement_NOSETTLE    Settlement = 0
	Settlement_REDSETTLE   Settlement = 1
	Settlement_GREENSETTLE Settlement = 2
	Settlement_BLUESETTLE  Settlement = 3
)

var Settlement_name = map[int32]string{
	0: "NOSETTLE",
	1: "REDSETTLE",
	2: "GREENSETTLE",
	3: "BLUESETTLE",
}
var Settlement_value = map[string]int32{
	"NOSETTLE":    0,
	"REDSETTLE":   1,
	"GREENSETTLE": 2,
	"BLUESETTLE":  3,
}

func (x Settlement) String() string {
	return proto.EnumName(Settlement_name, int32(x))
}
func (Settlement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{0}
}

type Road int32

const (
	Road_NOROAD    Road = 0
	Road_REDROAD   Road = 1
	Road_GREENROAD Road = 2
	Road_BLUEROAD  Road = 3
)

var Road_name = map[int32]string{
	0: "NOROAD",
	1: "REDROAD",
	2: "GREENROAD",
	3: "BLUEROAD",
}
var Road_value = map[string]int32{
	"NOROAD":    0,
	"REDROAD":   1,
	"GREENROAD": 2,
	"BLUEROAD":  3,
}

func (x Road) String() string {
	return proto.EnumName(Road_name, int32(x))
}
func (Road) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{1}
}

type Player int32

const (
	Player_RED   Player = 0
	Player_GREEN Player = 1
	Player_BLUE  Player = 2
)

var Player_name = map[int32]string{
	0: "RED",
	1: "GREEN",
	2: "BLUE",
}
var Player_value = map[string]int32{
	"RED":   0,
	"GREEN": 1,
	"BLUE":  2,
}

func (x Player) String() string {
	return proto.EnumName(Player_name, int32(x))
}
func (Player) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{2}
}

type GameState int32

const (
	GameState_JOINING GameState = 0
	GameState_RROLL   GameState = 1
	GameState_RTRADE  GameState = 2
	GameState_RDEV    GameState = 3
	GameState_BROLL   GameState = 4
	GameState_BTRADE  GameState = 5
	GameState_BDEV    GameState = 6
	GameState_GROLL   GameState = 7
	GameState_GTRADE  GameState = 8
	GameState_GDEV    GameState = 9
	GameState_RWON    GameState = 10
	GameState_BWON    GameState = 11
	GameState_GWON    GameState = 12
)

var GameState_name = map[int32]string{
	0:  "JOINING",
	1:  "RROLL",
	2:  "RTRADE",
	3:  "RDEV",
	4:  "BROLL",
	5:  "BTRADE",
	6:  "BDEV",
	7:  "GROLL",
	8:  "GTRADE",
	9:  "GDEV",
	10: "RWON",
	11: "BWON",
	12: "GWON",
}
var GameState_value = map[string]int32{
	"JOINING": 0,
	"RROLL":   1,
	"RTRADE":  2,
	"RDEV":    3,
	"BROLL":   4,
	"BTRADE":  5,
	"BDEV":    6,
	"GROLL":   7,
	"GTRADE":  8,
	"GDEV":    9,
	"RWON":    10,
	"BWON":    11,
	"GWON":    12,
}

func (x GameState) String() string {
	return proto.EnumName(GameState_name, int32(x))
}
func (GameState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{3}
}

type Resource_ResourceType int32

const (
	Resource_HILL     Resource_ResourceType = 0
	Resource_FOREST   Resource_ResourceType = 1
	Resource_MOUNTAIN Resource_ResourceType = 2
	Resource_FIELD    Resource_ResourceType = 3
	Resource_PASTURE  Resource_ResourceType = 4
	Resource_CAMP     Resource_ResourceType = 5
)

var Resource_ResourceType_name = map[int32]string{
	0: "HILL",
	1: "FOREST",
	2: "MOUNTAIN",
	3: "FIELD",
	4: "PASTURE",
	5: "CAMP",
}
var Resource_ResourceType_value = map[string]int32{
	"HILL":     0,
	"FOREST":   1,
	"MOUNTAIN": 2,
	"FIELD":    3,
	"PASTURE":  4,
	"CAMP":     5,
}

func (x Resource_ResourceType) String() string {
	return proto.EnumName(Resource_ResourceType_name, int32(x))
}
func (Resource_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{2, 0}
}

type IntersectionAttributes struct {
	Settlement           Settlement `protobuf:"varint,1,opt,name=settlement,proto3,enum=tfc.Settlement" json:"settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IntersectionAttributes) Reset()         { *m = IntersectionAttributes{} }
func (m *IntersectionAttributes) String() string { return proto.CompactTextString(m) }
func (*IntersectionAttributes) ProtoMessage()    {}
func (*IntersectionAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{0}
}
func (m *IntersectionAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntersectionAttributes.Unmarshal(m, b)
}
func (m *IntersectionAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntersectionAttributes.Marshal(b, m, deterministic)
}
func (dst *IntersectionAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntersectionAttributes.Merge(dst, src)
}
func (m *IntersectionAttributes) XXX_Size() int {
	return xxx_messageInfo_IntersectionAttributes.Size(m)
}
func (m *IntersectionAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_IntersectionAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_IntersectionAttributes proto.InternalMessageInfo

func (m *IntersectionAttributes) GetSettlement() Settlement {
	if m != nil {
		return m.Settlement
	}
	return Settlement_NOSETTLE
}

type Intersection struct {
	Id                   int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncidentEdge         int32                   `protobuf:"varint,2,opt,name=incidentEdge,proto3" json:"incidentEdge,omitempty"`
	Attributes           *IntersectionAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Coordinates          string                  `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Intersection) Reset()         { *m = Intersection{} }
func (m *Intersection) String() string { return proto.CompactTextString(m) }
func (*Intersection) ProtoMessage()    {}
func (*Intersection) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{1}
}
func (m *Intersection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intersection.Unmarshal(m, b)
}
func (m *Intersection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intersection.Marshal(b, m, deterministic)
}
func (dst *Intersection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intersection.Merge(dst, src)
}
func (m *Intersection) XXX_Size() int {
	return xxx_messageInfo_Intersection.Size(m)
}
func (m *Intersection) XXX_DiscardUnknown() {
	xxx_messageInfo_Intersection.DiscardUnknown(m)
}

var xxx_messageInfo_Intersection proto.InternalMessageInfo

func (m *Intersection) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intersection) GetIncidentEdge() int32 {
	if m != nil {
		return m.IncidentEdge
	}
	return 0
}

func (m *Intersection) GetAttributes() *IntersectionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Intersection) GetCoordinates() string {
	if m != nil {
		return m.Coordinates
	}
	return ""
}

type Resource struct {
	Type                 Resource_ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=tfc.Resource_ResourceType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{2}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() Resource_ResourceType {
	if m != nil {
		return m.Type
	}
	return Resource_HILL
}

type TileAttributes struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	RollNumber           int32     `protobuf:"varint,2,opt,name=rollNumber,proto3" json:"rollNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TileAttributes) Reset()         { *m = TileAttributes{} }
func (m *TileAttributes) String() string { return proto.CompactTextString(m) }
func (*TileAttributes) ProtoMessage()    {}
func (*TileAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{3}
}
func (m *TileAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileAttributes.Unmarshal(m, b)
}
func (m *TileAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileAttributes.Marshal(b, m, deterministic)
}
func (dst *TileAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileAttributes.Merge(dst, src)
}
func (m *TileAttributes) XXX_Size() int {
	return xxx_messageInfo_TileAttributes.Size(m)
}
func (m *TileAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_TileAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_TileAttributes proto.InternalMessageInfo

func (m *TileAttributes) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *TileAttributes) GetRollNumber() int32 {
	if m != nil {
		return m.RollNumber
	}
	return 0
}

type Tile struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OuterComponent       int32           `protobuf:"varint,2,opt,name=outerComponent,proto3" json:"outerComponent,omitempty"`
	Attributes           *TileAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{4}
}
func (m *Tile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tile.Unmarshal(m, b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
}
func (dst *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(dst, src)
}
func (m *Tile) XXX_Size() int {
	return xxx_messageInfo_Tile.Size(m)
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tile) GetOuterComponent() int32 {
	if m != nil {
		return m.OuterComponent
	}
	return 0
}

func (m *Tile) GetAttributes() *TileAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type EdgeAttributes struct {
	Road                 Road     `protobuf:"varint,1,opt,name=road,proto3,enum=tfc.Road" json:"road,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeAttributes) Reset()         { *m = EdgeAttributes{} }
func (m *EdgeAttributes) String() string { return proto.CompactTextString(m) }
func (*EdgeAttributes) ProtoMessage()    {}
func (*EdgeAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{5}
}
func (m *EdgeAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeAttributes.Unmarshal(m, b)
}
func (m *EdgeAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeAttributes.Marshal(b, m, deterministic)
}
func (dst *EdgeAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeAttributes.Merge(dst, src)
}
func (m *EdgeAttributes) XXX_Size() int {
	return xxx_messageInfo_EdgeAttributes.Size(m)
}
func (m *EdgeAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeAttributes proto.InternalMessageInfo

func (m *EdgeAttributes) GetRoad() Road {
	if m != nil {
		return m.Road
	}
	return Road_NOROAD
}

type Edge struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               int32           `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Twin                 int32           `protobuf:"varint,3,opt,name=twin,proto3" json:"twin,omitempty"`
	IncidentTile         int32           `protobuf:"varint,4,opt,name=incidentTile,proto3" json:"incidentTile,omitempty"`
	Next                 int32           `protobuf:"varint,5,opt,name=next,proto3" json:"next,omitempty"`
	Prev                 int32           `protobuf:"varint,6,opt,name=prev,proto3" json:"prev,omitempty"`
	Attributes           *EdgeAttributes `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{6}
}
func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (dst *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(dst, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Edge) GetOrigin() int32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Edge) GetTwin() int32 {
	if m != nil {
		return m.Twin
	}
	return 0
}

func (m *Edge) GetIncidentTile() int32 {
	if m != nil {
		return m.IncidentTile
	}
	return 0
}

func (m *Edge) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *Edge) GetPrev() int32 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *Edge) GetAttributes() *EdgeAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type GameBoard struct {
	Intersections        map[int32]*Intersection `protobuf:"bytes,1,rep,name=intersections,proto3" json:"intersections,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tiles                map[int32]*Tile         `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                map[int32]*Edge         `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GameBoard) Reset()         { *m = GameBoard{} }
func (m *GameBoard) String() string { return proto.CompactTextString(m) }
func (*GameBoard) ProtoMessage()    {}
func (*GameBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{7}
}
func (m *GameBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBoard.Unmarshal(m, b)
}
func (m *GameBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBoard.Marshal(b, m, deterministic)
}
func (dst *GameBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBoard.Merge(dst, src)
}
func (m *GameBoard) XXX_Size() int {
	return xxx_messageInfo_GameBoard.Size(m)
}
func (m *GameBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBoard.DiscardUnknown(m)
}

var xxx_messageInfo_GameBoard proto.InternalMessageInfo

func (m *GameBoard) GetIntersections() map[int32]*Intersection {
	if m != nil {
		return m.Intersections
	}
	return nil
}

func (m *GameBoard) GetTiles() map[int32]*Tile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

func (m *GameBoard) GetEdges() map[int32]*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type PlayerProfile struct {
	Resources            map[int32]int32 `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	WinningPoints        int32           `protobuf:"varint,2,opt,name=winningPoints,proto3" json:"winningPoints,omitempty"`
	Settlements          int32           `protobuf:"varint,3,opt,name=settlements,proto3" json:"settlements,omitempty"`
	Roads                int32           `protobuf:"varint,4,opt,name=roads,proto3" json:"roads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlayerProfile) Reset()         { *m = PlayerProfile{} }
func (m *PlayerProfile) String() string { return proto.CompactTextString(m) }
func (*PlayerProfile) ProtoMessage()    {}
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{8}
}
func (m *PlayerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerProfile.Unmarshal(m, b)
}
func (m *PlayerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerProfile.Marshal(b, m, deterministic)
}
func (dst *PlayerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerProfile.Merge(dst, src)
}
func (m *PlayerProfile) XXX_Size() int {
	return xxx_messageInfo_PlayerProfile.Size(m)
}
func (m *PlayerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerProfile proto.InternalMessageInfo

func (m *PlayerProfile) GetResources() map[int32]int32 {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *PlayerProfile) GetWinningPoints() int32 {
	if m != nil {
		return m.WinningPoints
	}
	return 0
}

func (m *PlayerProfile) GetSettlements() int32 {
	if m != nil {
		return m.Settlements
	}
	return 0
}

func (m *PlayerProfile) GetRoads() int32 {
	if m != nil {
		return m.Roads
	}
	return 0
}

type GameData struct {
	Board                *GameBoard               `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Profiles             map[int32]*PlayerProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	State                GameState                `protobuf:"varint,3,opt,name=state,proto3,enum=tfc.GameState" json:"state,omitempty"`
	IdentityMap          map[int32][]byte         `protobuf:"bytes,4,rep,name=identityMap,proto3" json:"identityMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GameData) Reset()         { *m = GameData{} }
func (m *GameData) String() string { return proto.CompactTextString(m) }
func (*GameData) ProtoMessage()    {}
func (*GameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_3d7caa2a700eac06, []int{9}
}
func (m *GameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameData.Unmarshal(m, b)
}
func (m *GameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameData.Marshal(b, m, deterministic)
}
func (dst *GameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameData.Merge(dst, src)
}
func (m *GameData) XXX_Size() int {
	return xxx_messageInfo_GameData.Size(m)
}
func (m *GameData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameData.DiscardUnknown(m)
}

var xxx_messageInfo_GameData proto.InternalMessageInfo

func (m *GameData) GetBoard() *GameBoard {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *GameData) GetProfiles() map[int32]*PlayerProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *GameData) GetState() GameState {
	if m != nil {
		return m.State
	}
	return GameState_JOINING
}

func (m *GameData) GetIdentityMap() map[int32][]byte {
	if m != nil {
		return m.IdentityMap
	}
	return nil
}

func init() {
	proto.RegisterType((*IntersectionAttributes)(nil), "tfc.IntersectionAttributes")
	proto.RegisterType((*Intersection)(nil), "tfc.Intersection")
	proto.RegisterType((*Resource)(nil), "tfc.Resource")
	proto.RegisterType((*TileAttributes)(nil), "tfc.TileAttributes")
	proto.RegisterType((*Tile)(nil), "tfc.Tile")
	proto.RegisterType((*EdgeAttributes)(nil), "tfc.EdgeAttributes")
	proto.RegisterType((*Edge)(nil), "tfc.Edge")
	proto.RegisterType((*GameBoard)(nil), "tfc.GameBoard")
	proto.RegisterMapType((map[int32]*Edge)(nil), "tfc.GameBoard.EdgesEntry")
	proto.RegisterMapType((map[int32]*Intersection)(nil), "tfc.GameBoard.IntersectionsEntry")
	proto.RegisterMapType((map[int32]*Tile)(nil), "tfc.GameBoard.TilesEntry")
	proto.RegisterType((*PlayerProfile)(nil), "tfc.PlayerProfile")
	proto.RegisterMapType((map[int32]int32)(nil), "tfc.PlayerProfile.ResourcesEntry")
	proto.RegisterType((*GameData)(nil), "tfc.GameData")
	proto.RegisterMapType((map[int32][]byte)(nil), "tfc.GameData.IdentityMapEntry")
	proto.RegisterMapType((map[int32]*PlayerProfile)(nil), "tfc.GameData.ProfilesEntry")
	proto.RegisterEnum("tfc.Settlement", Settlement_name, Settlement_value)
	proto.RegisterEnum("tfc.Road", Road_name, Road_value)
	proto.RegisterEnum("tfc.Player", Player_name, Player_value)
	proto.RegisterEnum("tfc.GameState", GameState_name, GameState_value)
	proto.RegisterEnum("tfc.Resource_ResourceType", Resource_ResourceType_name, Resource_ResourceType_value)
}

func init() { proto.RegisterFile("gamedata.proto", fileDescriptor_gamedata_3d7caa2a700eac06) }

var fileDescriptor_gamedata_3d7caa2a700eac06 = []byte{
	// 964 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xc7, 0x71, 0x9c, 0x4d, 0x5e, 0xb2, 0xae, 0x19, 0xaa, 0x2a, 0xa4, 0xa2, 0x14, 0x0b, 0x95,
	0xb2, 0x87, 0x54, 0xda, 0x1e, 0x40, 0x50, 0x01, 0xd9, 0x8d, 0x1b, 0x52, 0x65, 0xed, 0x68, 0xe2,
	0x85, 0x03, 0x27, 0x6f, 0x32, 0x5d, 0x59, 0x64, 0xed, 0xc8, 0xf6, 0x16, 0xf2, 0x2d, 0xb8, 0x70,
	0xe0, 0xc8, 0x67, 0xe1, 0x9b, 0x70, 0xe6, 0x43, 0xf0, 0xde, 0x78, 0xd6, 0x19, 0x67, 0x23, 0xc1,
	0x6d, 0xfc, 0xe6, 0xf7, 0xfb, 0xbd, 0xbf, 0x33, 0x63, 0xb0, 0xaf, 0xa3, 0x1b, 0xb1, 0x8a, 0x8a,
	0x68, 0xb8, 0xc9, 0xd2, 0x22, 0x65, 0x66, 0xf1, 0x76, 0xe9, 0x4e, 0xe1, 0xd1, 0x34, 0x29, 0x44,
	0x96, 0x8b, 0x65, 0x11, 0xa7, 0xc9, 0xa8, 0x28, 0xb2, 0xf8, 0xea, 0xb6, 0x10, 0x39, 0x7b, 0x01,
	0x90, 0x8b, 0xa2, 0x58, 0x8b, 0x1b, 0x91, 0x14, 0x7d, 0xe3, 0xa9, 0xf1, 0xdc, 0x3e, 0x7d, 0x30,
	0x44, 0xce, 0x70, 0x51, 0x99, 0xb9, 0x06, 0x71, 0xff, 0x34, 0xa0, 0xa7, 0x6b, 0x31, 0x1b, 0x1a,
	0xf1, 0x4a, 0x32, 0x2d, 0x8e, 0x2b, 0xe6, 0x42, 0x2f, 0x4e, 0x96, 0xf1, 0x0a, 0xc1, 0xde, 0xea,
	0x5a, 0xf4, 0x1b, 0x72, 0xa7, 0x66, 0x63, 0x5f, 0x03, 0x44, 0x55, 0x0c, 0x7d, 0x13, 0x11, 0xdd,
	0xd3, 0xc7, 0xd2, 0xeb, 0xe1, 0x30, 0xb9, 0x06, 0x67, 0x4f, 0xa1, 0xbb, 0x4c, 0xd3, 0x6c, 0x15,
	0x27, 0x11, 0xb1, 0x2d, 0x64, 0x77, 0xb8, 0x6e, 0x72, 0x7f, 0x33, 0xa0, 0xcd, 0x45, 0x9e, 0xde,
	0x66, 0x4b, 0xc1, 0x86, 0xd0, 0x2c, 0xb6, 0x1b, 0xa1, 0x72, 0x1b, 0x48, 0x2f, 0x77, 0x9b, 0xd5,
	0x22, 0x44, 0x04, 0x97, 0x38, 0x37, 0x84, 0x9e, 0x6e, 0x65, 0x6d, 0x68, 0x7e, 0x3f, 0x9d, 0xcd,
	0x9c, 0xf7, 0x18, 0x40, 0xeb, 0x75, 0xc0, 0xbd, 0x45, 0xe8, 0x18, 0xac, 0x07, 0xed, 0x8b, 0xe0,
	0xd2, 0x0f, 0x47, 0x53, 0xdf, 0x69, 0xb0, 0x0e, 0x58, 0xaf, 0xa7, 0xde, 0x6c, 0xec, 0x98, 0xac,
	0x0b, 0x47, 0xf3, 0xd1, 0x22, 0xbc, 0xe4, 0x9e, 0xd3, 0x24, 0xee, 0xf9, 0xe8, 0x62, 0xee, 0x58,
	0xee, 0x4f, 0x60, 0x87, 0xf1, 0x5a, 0x68, 0x95, 0xff, 0x1c, 0xda, 0x99, 0xf2, 0x23, 0x63, 0xeb,
	0x9e, 0x1e, 0xd7, 0x62, 0xe3, 0xd5, 0x36, 0x7b, 0x02, 0x90, 0xa5, 0xeb, 0xb5, 0x7f, 0x7b, 0x73,
	0x25, 0x32, 0x55, 0x50, 0xcd, 0xe2, 0xe6, 0xd0, 0x24, 0xf1, 0x7b, 0xad, 0x78, 0x06, 0x76, 0x8a,
	0xbe, 0xb2, 0xf3, 0xf4, 0x66, 0x93, 0x26, 0xd4, 0xe0, 0x92, 0xbb, 0x67, 0x65, 0x2f, 0x0f, 0xb4,
	0xe3, 0x03, 0x19, 0x4c, 0x3d, 0x66, 0xbd, 0x0d, 0xee, 0x0b, 0xb0, 0xa9, 0x97, 0x5a, 0x46, 0x1f,
	0x41, 0x33, 0x4b, 0xa3, 0x95, 0xaa, 0x74, 0xa7, 0xcc, 0x06, 0x0d, 0x5c, 0x9a, 0xdd, 0xbf, 0x0c,
	0x68, 0xca, 0xee, 0xef, 0x87, 0xf9, 0x08, 0x5a, 0x69, 0x16, 0x5f, 0xc7, 0x89, 0x0a, 0x4f, 0x7d,
	0x31, 0x86, 0x9d, 0xfb, 0x05, 0xad, 0xa6, 0xb4, 0xca, 0xb5, 0x3e, 0x5d, 0x14, 0x5b, 0xbf, 0x59,
	0x9f, 0x2e, 0x59, 0x06, 0xe4, 0x25, 0xe2, 0xd7, 0x42, 0x4e, 0x06, 0xf2, 0x68, 0x4d, 0xb6, 0x4d,
	0x26, 0xde, 0xf5, 0x5b, 0xa5, 0x8d, 0xd6, 0x7b, 0x69, 0x1f, 0x69, 0x69, 0xd7, 0x13, 0xab, 0xa5,
	0xfd, 0xbb, 0x09, 0x9d, 0x09, 0x1e, 0xb1, 0xb3, 0x34, 0xca, 0x56, 0x6c, 0x02, 0xc7, 0xb1, 0x36,
	0xb1, 0x39, 0x66, 0x65, 0xa2, 0xca, 0x27, 0x52, 0xa5, 0x82, 0xd5, 0xa6, 0x3a, 0xf7, 0x92, 0x22,
	0xdb, 0xf2, 0x3a, 0x0f, 0xcf, 0xa1, 0x55, 0x60, 0xec, 0x39, 0x96, 0x80, 0x04, 0x3e, 0xdc, 0x13,
	0xa0, 0xbc, 0x14, 0xb1, 0xc4, 0x11, 0x41, 0x60, 0x94, 0xd4, 0xae, 0x43, 0x04, 0xca, 0xe0, 0x8e,
	0x20, 0x71, 0x83, 0x05, 0xb0, 0xfb, 0x61, 0x30, 0x07, 0xcc, 0x9f, 0xc5, 0x56, 0x35, 0x83, 0x96,
	0xec, 0x33, 0xb0, 0xde, 0x45, 0xeb, 0xdb, 0xf2, 0xe0, 0x76, 0x4f, 0xdf, 0xbf, 0x77, 0x2c, 0x79,
	0xb9, 0xff, 0x55, 0xe3, 0x4b, 0x63, 0x70, 0x0e, 0xb0, 0x0b, 0xed, 0x80, 0xd8, 0xc7, 0x75, 0xb1,
	0x4e, 0x35, 0x54, 0x7b, 0x22, 0xbb, 0x70, 0xff, 0xaf, 0x08, 0x31, 0x34, 0x11, 0xf7, 0x1f, 0x03,
	0x8e, 0xe7, 0xeb, 0x68, 0x2b, 0xb2, 0x79, 0x96, 0xbe, 0xa5, 0x31, 0xf8, 0x16, 0x3a, 0x77, 0x27,
	0xa8, 0xde, 0x97, 0x1a, 0xac, 0x3a, 0x6f, 0xaa, 0x5a, 0x3b, 0x0e, 0xfb, 0x14, 0x8e, 0x71, 0xe4,
	0x92, 0x38, 0xb9, 0x9e, 0xa7, 0xd8, 0xad, 0x5c, 0x8d, 0x67, 0xdd, 0x48, 0xd7, 0xd1, 0xee, 0x7a,
	0xcc, 0xd5, 0xb0, 0xea, 0x26, 0xf6, 0x10, 0x2c, 0x3a, 0x00, 0xb9, 0x1a, 0xd6, 0xf2, 0x63, 0xf0,
	0x0a, 0xec, 0xba, 0xeb, 0x03, 0x99, 0x3f, 0xd4, 0x33, 0xb7, 0xf4, 0x74, 0xff, 0x6e, 0x40, 0x9b,
	0xba, 0x3d, 0xc6, 0x9b, 0x1e, 0x03, 0xb5, 0xae, 0xa8, 0xeb, 0xea, 0x1e, 0xb1, 0xeb, 0xb3, 0xc0,
	0xcb, 0x4d, 0xf6, 0x05, 0xb4, 0x37, 0x65, 0xce, 0x77, 0x53, 0xf6, 0xb8, 0x02, 0x92, 0xcc, 0x50,
	0x55, 0x44, 0x15, 0xa2, 0x02, 0x93, 0x7c, 0x5e, 0xe0, 0xc5, 0x2a, 0x73, 0xb3, 0x35, 0xf9, 0x05,
	0x59, 0x79, 0xb9, 0xc9, 0xbe, 0x83, 0xae, 0x3c, 0x82, 0x71, 0xb1, 0xbd, 0x88, 0x36, 0x98, 0x2b,
	0x79, 0x78, 0x52, 0xf7, 0x30, 0xdd, 0x01, 0x4a, 0x27, 0x3a, 0x65, 0x10, 0x60, 0x07, 0xf5, 0x10,
	0x0e, 0x14, 0xe4, 0x79, 0x7d, 0x14, 0xd8, 0xfd, 0x7e, 0xea, 0x83, 0xf5, 0x0d, 0x38, 0xfb, 0x1e,
	0xff, 0xab, 0xc8, 0x3d, 0x8d, 0x7f, 0xf2, 0x06, 0x60, 0xf7, 0x0a, 0xd2, 0x95, 0xef, 0x07, 0x0b,
	0x2f, 0x0c, 0x67, 0x1e, 0x3e, 0x06, 0xc7, 0xd0, 0xe1, 0xde, 0x58, 0x7d, 0x1a, 0xec, 0x01, 0x74,
	0x27, 0xdc, 0xf3, 0x7c, 0x65, 0x68, 0xe0, 0x25, 0x07, 0x67, 0xb3, 0x4b, 0x4f, 0x7d, 0x9b, 0x27,
	0xaf, 0xa0, 0x49, 0x77, 0x21, 0x3d, 0x22, 0x7e, 0xc0, 0x83, 0xd1, 0x18, 0x35, 0xf0, 0xad, 0x40,
	0x0d, 0xf9, 0x61, 0x90, 0xa0, 0x54, 0x90, 0x9f, 0x0d, 0xf2, 0x46, 0x7c, 0xf9, 0x65, 0x9e, 0x3c,
	0x83, 0x56, 0x99, 0x25, 0x3b, 0x02, 0x13, 0x39, 0x48, 0xc6, 0x37, 0x47, 0xe2, 0x91, 0x8a, 0xcf,
	0x0c, 0x61, 0x9d, 0xc6, 0xc9, 0x1f, 0x46, 0x79, 0x3b, 0xc9, 0xce, 0x90, 0xfe, 0x9b, 0x60, 0xea,
	0x4f, 0xfd, 0x49, 0x89, 0xe7, 0x3c, 0xc0, 0x87, 0xcc, 0xa0, 0x18, 0x78, 0xc8, 0x47, 0x63, 0x8a,
	0x13, 0xb9, 0x7c, 0xec, 0xfd, 0x80, 0x2f, 0x17, 0x02, 0xce, 0x24, 0xa0, 0x49, 0x80, 0xb3, 0x12,
	0x60, 0x49, 0x71, 0x02, 0xb4, 0x4a, 0x8f, 0x04, 0x38, 0x22, 0xc0, 0xa4, 0x04, 0xb4, 0x09, 0x30,
	0x21, 0x40, 0x47, 0x6a, 0xfd, 0x18, 0xf8, 0x0e, 0x48, 0x12, 0xad, 0xba, 0x72, 0x97, 0x56, 0xbd,
	0xab, 0x96, 0xfc, 0x21, 0x79, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x31, 0x27, 0x21,
	0xa2, 0x08, 0x00, 0x00,
}
