// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedata.proto

package tfc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Settlement int32

const (
	Settlement_NOSETTLE    Settlement = 0
	Settlement_REDSETTLE   Settlement = 1
	Settlement_GREENSETTLE Settlement = 2
	Settlement_BLUESETTLE  Settlement = 3
)

var Settlement_name = map[int32]string{
	0: "NOSETTLE",
	1: "REDSETTLE",
	2: "GREENSETTLE",
	3: "BLUESETTLE",
}
var Settlement_value = map[string]int32{
	"NOSETTLE":    0,
	"REDSETTLE":   1,
	"GREENSETTLE": 2,
	"BLUESETTLE":  3,
}

func (x Settlement) String() string {
	return proto.EnumName(Settlement_name, int32(x))
}
func (Settlement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{0}
}

type Resource int32

const (
	Resource_HILL     Resource = 0
	Resource_FOREST   Resource = 1
	Resource_MOUNTAIN Resource = 2
	Resource_FIELD    Resource = 3
	Resource_PASTURE  Resource = 4
	Resource_CAMP     Resource = 5
)

var Resource_name = map[int32]string{
	0: "HILL",
	1: "FOREST",
	2: "MOUNTAIN",
	3: "FIELD",
	4: "PASTURE",
	5: "CAMP",
}
var Resource_value = map[string]int32{
	"HILL":     0,
	"FOREST":   1,
	"MOUNTAIN": 2,
	"FIELD":    3,
	"PASTURE":  4,
	"CAMP":     5,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}
func (Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{1}
}

type Road int32

const (
	Road_NOROAD    Road = 0
	Road_REDROAD   Road = 1
	Road_GREENROAD Road = 2
	Road_BLUEROAD  Road = 3
)

var Road_name = map[int32]string{
	0: "NOROAD",
	1: "REDROAD",
	2: "GREENROAD",
	3: "BLUEROAD",
}
var Road_value = map[string]int32{
	"NOROAD":    0,
	"REDROAD":   1,
	"GREENROAD": 2,
	"BLUEROAD":  3,
}

func (x Road) String() string {
	return proto.EnumName(Road_name, int32(x))
}
func (Road) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{2}
}

type Player int32

const (
	Player_RED   Player = 0
	Player_GREEN Player = 1
	Player_BLUE  Player = 2
)

var Player_name = map[int32]string{
	0: "RED",
	1: "GREEN",
	2: "BLUE",
}
var Player_value = map[string]int32{
	"RED":   0,
	"GREEN": 1,
	"BLUE":  2,
}

func (x Player) String() string {
	return proto.EnumName(Player_name, int32(x))
}
func (Player) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{3}
}

type GameState int32

const (
	GameState_JOINING GameState = 0
	GameState_RROLL   GameState = 1
	GameState_RTRADE  GameState = 2
	GameState_RDEV    GameState = 3
	GameState_BROLL   GameState = 4
	GameState_BTRADE  GameState = 5
	GameState_BDEV    GameState = 6
	GameState_GROLL   GameState = 7
	GameState_GTRADE  GameState = 8
	GameState_GDEV    GameState = 9
	GameState_RWON    GameState = 10
	GameState_BWON    GameState = 11
	GameState_GWON    GameState = 12
)

var GameState_name = map[int32]string{
	0:  "JOINING",
	1:  "RROLL",
	2:  "RTRADE",
	3:  "RDEV",
	4:  "BROLL",
	5:  "BTRADE",
	6:  "BDEV",
	7:  "GROLL",
	8:  "GTRADE",
	9:  "GDEV",
	10: "RWON",
	11: "BWON",
	12: "GWON",
}
var GameState_value = map[string]int32{
	"JOINING": 0,
	"RROLL":   1,
	"RTRADE":  2,
	"RDEV":    3,
	"BROLL":   4,
	"BTRADE":  5,
	"BDEV":    6,
	"GROLL":   7,
	"GTRADE":  8,
	"GDEV":    9,
	"RWON":    10,
	"BWON":    11,
	"GWON":    12,
}

func (x GameState) String() string {
	return proto.EnumName(GameState_name, int32(x))
}
func (GameState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{4}
}

type IntersectionAttributes struct {
	Settlement           Settlement `protobuf:"varint,1,opt,name=settlement,proto3,enum=tfc.Settlement" json:"settlement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IntersectionAttributes) Reset()         { *m = IntersectionAttributes{} }
func (m *IntersectionAttributes) String() string { return proto.CompactTextString(m) }
func (*IntersectionAttributes) ProtoMessage()    {}
func (*IntersectionAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{0}
}
func (m *IntersectionAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntersectionAttributes.Unmarshal(m, b)
}
func (m *IntersectionAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntersectionAttributes.Marshal(b, m, deterministic)
}
func (dst *IntersectionAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntersectionAttributes.Merge(dst, src)
}
func (m *IntersectionAttributes) XXX_Size() int {
	return xxx_messageInfo_IntersectionAttributes.Size(m)
}
func (m *IntersectionAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_IntersectionAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_IntersectionAttributes proto.InternalMessageInfo

func (m *IntersectionAttributes) GetSettlement() Settlement {
	if m != nil {
		return m.Settlement
	}
	return Settlement_NOSETTLE
}

type Coord struct {
	X                    int32    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    int32    `protobuf:"varint,3,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{1}
}
func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (dst *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(dst, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coord) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Coord) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Intersection struct {
	Id                   uint32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncidentEdge         uint32                  `protobuf:"varint,2,opt,name=incidentEdge,proto3" json:"incidentEdge,omitempty"`
	Attributes           *IntersectionAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Coordinates          *Coord                  `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	LastUpdated          *timestamp.Timestamp    `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Intersection) Reset()         { *m = Intersection{} }
func (m *Intersection) String() string { return proto.CompactTextString(m) }
func (*Intersection) ProtoMessage()    {}
func (*Intersection) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{2}
}
func (m *Intersection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intersection.Unmarshal(m, b)
}
func (m *Intersection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intersection.Marshal(b, m, deterministic)
}
func (dst *Intersection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intersection.Merge(dst, src)
}
func (m *Intersection) XXX_Size() int {
	return xxx_messageInfo_Intersection.Size(m)
}
func (m *Intersection) XXX_DiscardUnknown() {
	xxx_messageInfo_Intersection.DiscardUnknown(m)
}

var xxx_messageInfo_Intersection proto.InternalMessageInfo

func (m *Intersection) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intersection) GetIncidentEdge() uint32 {
	if m != nil {
		return m.IncidentEdge
	}
	return 0
}

func (m *Intersection) GetAttributes() *IntersectionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Intersection) GetCoordinates() *Coord {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Intersection) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type TileAttributes struct {
	Resource             Resource             `protobuf:"varint,1,opt,name=resource,proto3,enum=tfc.Resource" json:"resource,omitempty"`
	RollNumber           int32                `protobuf:"varint,2,opt,name=rollNumber,proto3" json:"rollNumber,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TileAttributes) Reset()         { *m = TileAttributes{} }
func (m *TileAttributes) String() string { return proto.CompactTextString(m) }
func (*TileAttributes) ProtoMessage()    {}
func (*TileAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{3}
}
func (m *TileAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileAttributes.Unmarshal(m, b)
}
func (m *TileAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileAttributes.Marshal(b, m, deterministic)
}
func (dst *TileAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileAttributes.Merge(dst, src)
}
func (m *TileAttributes) XXX_Size() int {
	return xxx_messageInfo_TileAttributes.Size(m)
}
func (m *TileAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_TileAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_TileAttributes proto.InternalMessageInfo

func (m *TileAttributes) GetResource() Resource {
	if m != nil {
		return m.Resource
	}
	return Resource_HILL
}

func (m *TileAttributes) GetRollNumber() int32 {
	if m != nil {
		return m.RollNumber
	}
	return 0
}

func (m *TileAttributes) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Tile struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OuterComponent       uint32               `protobuf:"varint,2,opt,name=outerComponent,proto3" json:"outerComponent,omitempty"`
	Attributes           *TileAttributes      `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{4}
}
func (m *Tile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tile.Unmarshal(m, b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
}
func (dst *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(dst, src)
}
func (m *Tile) XXX_Size() int {
	return xxx_messageInfo_Tile.Size(m)
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tile) GetOuterComponent() uint32 {
	if m != nil {
		return m.OuterComponent
	}
	return 0
}

func (m *Tile) GetAttributes() *TileAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Tile) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type EdgeAttributes struct {
	Road                 Road     `protobuf:"varint,1,opt,name=road,proto3,enum=tfc.Road" json:"road,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeAttributes) Reset()         { *m = EdgeAttributes{} }
func (m *EdgeAttributes) String() string { return proto.CompactTextString(m) }
func (*EdgeAttributes) ProtoMessage()    {}
func (*EdgeAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{5}
}
func (m *EdgeAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeAttributes.Unmarshal(m, b)
}
func (m *EdgeAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeAttributes.Marshal(b, m, deterministic)
}
func (dst *EdgeAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeAttributes.Merge(dst, src)
}
func (m *EdgeAttributes) XXX_Size() int {
	return xxx_messageInfo_EdgeAttributes.Size(m)
}
func (m *EdgeAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeAttributes proto.InternalMessageInfo

func (m *EdgeAttributes) GetRoad() Road {
	if m != nil {
		return m.Road
	}
	return Road_NOROAD
}

type Edge struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               uint32               `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Twin                 uint32               `protobuf:"varint,3,opt,name=twin,proto3" json:"twin,omitempty"`
	IncidentTile         uint32               `protobuf:"varint,4,opt,name=incidentTile,proto3" json:"incidentTile,omitempty"`
	Next                 uint32               `protobuf:"varint,5,opt,name=next,proto3" json:"next,omitempty"`
	Prev                 uint32               `protobuf:"varint,6,opt,name=prev,proto3" json:"prev,omitempty"`
	Orientation          string               `protobuf:"bytes,8,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Attributes           *EdgeAttributes      `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Edge) Reset()         { *m = Edge{} }
func (m *Edge) String() string { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()    {}
func (*Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{6}
}
func (m *Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edge.Unmarshal(m, b)
}
func (m *Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edge.Marshal(b, m, deterministic)
}
func (dst *Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edge.Merge(dst, src)
}
func (m *Edge) XXX_Size() int {
	return xxx_messageInfo_Edge.Size(m)
}
func (m *Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Edge proto.InternalMessageInfo

func (m *Edge) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Edge) GetOrigin() uint32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Edge) GetTwin() uint32 {
	if m != nil {
		return m.Twin
	}
	return 0
}

func (m *Edge) GetIncidentTile() uint32 {
	if m != nil {
		return m.IncidentTile
	}
	return 0
}

func (m *Edge) GetNext() uint32 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *Edge) GetPrev() uint32 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *Edge) GetOrientation() string {
	if m != nil {
		return m.Orientation
	}
	return ""
}

func (m *Edge) GetAttributes() *EdgeAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Edge) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type GameBoard struct {
	Intersections        map[uint32]*Intersection `protobuf:"bytes,1,rep,name=intersections,proto3" json:"intersections,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tiles                map[uint32]*Tile         `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                map[uint32]*Edge         `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GameBoard) Reset()         { *m = GameBoard{} }
func (m *GameBoard) String() string { return proto.CompactTextString(m) }
func (*GameBoard) ProtoMessage()    {}
func (*GameBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{7}
}
func (m *GameBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBoard.Unmarshal(m, b)
}
func (m *GameBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBoard.Marshal(b, m, deterministic)
}
func (dst *GameBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBoard.Merge(dst, src)
}
func (m *GameBoard) XXX_Size() int {
	return xxx_messageInfo_GameBoard.Size(m)
}
func (m *GameBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBoard.DiscardUnknown(m)
}

var xxx_messageInfo_GameBoard proto.InternalMessageInfo

func (m *GameBoard) GetIntersections() map[uint32]*Intersection {
	if m != nil {
		return m.Intersections
	}
	return nil
}

func (m *GameBoard) GetTiles() map[uint32]*Tile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

func (m *GameBoard) GetEdges() map[uint32]*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type PlayerProfile struct {
	Resources            map[int32]int32      `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	WinningPoints        int32                `protobuf:"varint,2,opt,name=winningPoints,proto3" json:"winningPoints,omitempty"`
	Settlements          int32                `protobuf:"varint,3,opt,name=settlements,proto3" json:"settlements,omitempty"`
	Roads                int32                `protobuf:"varint,4,opt,name=roads,proto3" json:"roads,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerProfile) Reset()         { *m = PlayerProfile{} }
func (m *PlayerProfile) String() string { return proto.CompactTextString(m) }
func (*PlayerProfile) ProtoMessage()    {}
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{8}
}
func (m *PlayerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerProfile.Unmarshal(m, b)
}
func (m *PlayerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerProfile.Marshal(b, m, deterministic)
}
func (dst *PlayerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerProfile.Merge(dst, src)
}
func (m *PlayerProfile) XXX_Size() int {
	return xxx_messageInfo_PlayerProfile.Size(m)
}
func (m *PlayerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerProfile proto.InternalMessageInfo

func (m *PlayerProfile) GetResources() map[int32]int32 {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *PlayerProfile) GetWinningPoints() int32 {
	if m != nil {
		return m.WinningPoints
	}
	return 0
}

func (m *PlayerProfile) GetSettlements() int32 {
	if m != nil {
		return m.Settlements
	}
	return 0
}

func (m *PlayerProfile) GetRoads() int32 {
	if m != nil {
		return m.Roads
	}
	return 0
}

func (m *PlayerProfile) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type GameData struct {
	Board                *GameBoard               `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Profiles             map[int32]*PlayerProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	State                GameState                `protobuf:"varint,3,opt,name=state,proto3,enum=tfc.GameState" json:"state,omitempty"`
	IdentityMap          map[int32][]byte         `protobuf:"bytes,4,rep,name=identityMap,proto3" json:"identityMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LastUpdated          *timestamp.Timestamp     `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GameData) Reset()         { *m = GameData{} }
func (m *GameData) String() string { return proto.CompactTextString(m) }
func (*GameData) ProtoMessage()    {}
func (*GameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamedata_ff87415c68ae5234, []int{9}
}
func (m *GameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameData.Unmarshal(m, b)
}
func (m *GameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameData.Marshal(b, m, deterministic)
}
func (dst *GameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameData.Merge(dst, src)
}
func (m *GameData) XXX_Size() int {
	return xxx_messageInfo_GameData.Size(m)
}
func (m *GameData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameData.DiscardUnknown(m)
}

var xxx_messageInfo_GameData proto.InternalMessageInfo

func (m *GameData) GetBoard() *GameBoard {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *GameData) GetProfiles() map[int32]*PlayerProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *GameData) GetState() GameState {
	if m != nil {
		return m.State
	}
	return GameState_JOINING
}

func (m *GameData) GetIdentityMap() map[int32][]byte {
	if m != nil {
		return m.IdentityMap
	}
	return nil
}

func (m *GameData) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*IntersectionAttributes)(nil), "tfc.IntersectionAttributes")
	proto.RegisterType((*Coord)(nil), "tfc.Coord")
	proto.RegisterType((*Intersection)(nil), "tfc.Intersection")
	proto.RegisterType((*TileAttributes)(nil), "tfc.TileAttributes")
	proto.RegisterType((*Tile)(nil), "tfc.Tile")
	proto.RegisterType((*EdgeAttributes)(nil), "tfc.EdgeAttributes")
	proto.RegisterType((*Edge)(nil), "tfc.Edge")
	proto.RegisterType((*GameBoard)(nil), "tfc.GameBoard")
	proto.RegisterMapType((map[uint32]*Edge)(nil), "tfc.GameBoard.EdgesEntry")
	proto.RegisterMapType((map[uint32]*Intersection)(nil), "tfc.GameBoard.IntersectionsEntry")
	proto.RegisterMapType((map[uint32]*Tile)(nil), "tfc.GameBoard.TilesEntry")
	proto.RegisterType((*PlayerProfile)(nil), "tfc.PlayerProfile")
	proto.RegisterMapType((map[int32]int32)(nil), "tfc.PlayerProfile.ResourcesEntry")
	proto.RegisterType((*GameData)(nil), "tfc.GameData")
	proto.RegisterMapType((map[int32][]byte)(nil), "tfc.GameData.IdentityMapEntry")
	proto.RegisterMapType((map[int32]*PlayerProfile)(nil), "tfc.GameData.ProfilesEntry")
	proto.RegisterEnum("tfc.Settlement", Settlement_name, Settlement_value)
	proto.RegisterEnum("tfc.Resource", Resource_name, Resource_value)
	proto.RegisterEnum("tfc.Road", Road_name, Road_value)
	proto.RegisterEnum("tfc.Player", Player_name, Player_value)
	proto.RegisterEnum("tfc.GameState", GameState_name, GameState_value)
}

func init() { proto.RegisterFile("gamedata.proto", fileDescriptor_gamedata_ff87415c68ae5234) }

var fileDescriptor_gamedata_ff87415c68ae5234 = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x8f, 0x22, 0x45,
	0x10, 0x76, 0x18, 0x86, 0x85, 0x1a, 0xe0, 0xb0, 0xbd, 0x5c, 0x70, 0x2f, 0xde, 0x9d, 0xc4, 0x9c,
	0xe7, 0xc6, 0xb0, 0x71, 0xef, 0x41, 0xa3, 0xe7, 0x0f, 0x76, 0x99, 0x43, 0x2e, 0xbb, 0x40, 0x1a,
	0x56, 0xef, 0xee, 0xc5, 0x0c, 0xd0, 0x4b, 0x26, 0xc2, 0x0c, 0x99, 0x69, 0x4e, 0xf7, 0x0f, 0xf1,
	0x41, 0xdf, 0x4c, 0x7c, 0xf3, 0xcd, 0xbf, 0xcb, 0x3f, 0xc2, 0xaa, 0xee, 0x01, 0x7a, 0x58, 0x12,
	0x4d, 0xd6, 0xb7, 0xee, 0xea, 0xef, 0xab, 0xae, 0xfa, 0xfa, 0x9b, 0x02, 0xa8, 0xce, 0xfc, 0x85,
	0x98, 0xfa, 0xd2, 0x6f, 0x2e, 0xe3, 0x48, 0x46, 0xcc, 0x96, 0x57, 0x93, 0xc3, 0x87, 0xb3, 0x28,
	0x9a, 0xcd, 0xc5, 0xb1, 0x0a, 0x8d, 0x57, 0x57, 0xc7, 0x32, 0x58, 0x88, 0x44, 0xfa, 0x8b, 0xa5,
	0x46, 0x35, 0xba, 0x70, 0xaf, 0x1b, 0x4a, 0x11, 0x27, 0x62, 0x22, 0x83, 0x28, 0x6c, 0x49, 0x19,
	0x07, 0xe3, 0x95, 0x14, 0x09, 0x3b, 0x06, 0x48, 0x84, 0x94, 0x73, 0xb1, 0x10, 0xa1, 0xac, 0x5b,
	0x8f, 0xac, 0x27, 0xd5, 0x93, 0x3b, 0x4d, 0x4c, 0xda, 0x1c, 0x6e, 0xc2, 0xdc, 0x80, 0x34, 0x3e,
	0x01, 0xe7, 0x2c, 0x8a, 0xe2, 0x29, 0x2b, 0x83, 0xf5, 0x52, 0x11, 0x1c, 0x6e, 0xbd, 0xa4, 0xdd,
	0xab, 0x7a, 0x4e, 0xef, 0x5e, 0xd1, 0xee, 0x75, 0xdd, 0xd6, 0xbb, 0xd7, 0x8d, 0xbf, 0x2d, 0x28,
	0x9b, 0xd7, 0xb3, 0x2a, 0xe4, 0x82, 0xa9, 0xe2, 0x56, 0x38, 0xae, 0x58, 0x03, 0xca, 0x41, 0x38,
	0x09, 0xa6, 0x98, 0xdf, 0x9b, 0xce, 0x84, 0xca, 0x53, 0xe1, 0x99, 0x18, 0xfb, 0x02, 0xc0, 0xdf,
	0x94, 0xad, 0x72, 0xbb, 0x27, 0xf7, 0x55, 0xa1, 0xfb, 0x3b, 0xe3, 0x06, 0x9c, 0x7d, 0x0c, 0xee,
	0x84, 0x8a, 0x0e, 0x42, 0x9f, 0xd8, 0x8e, 0x62, 0x83, 0x62, 0xab, 0x66, 0xb8, 0x79, 0xcc, 0xbe,
	0x84, 0xf2, 0xdc, 0x4f, 0xe4, 0x0f, 0xab, 0x25, 0x0a, 0x2d, 0xa6, 0xf5, 0x92, 0x82, 0x1f, 0x36,
	0xb5, 0xca, 0xcd, 0xb5, 0xca, 0xcd, 0xd1, 0x5a, 0x65, 0xee, 0x12, 0xfe, 0x52, 0xc3, 0x1b, 0xbf,
	0x59, 0x50, 0x1d, 0x05, 0x73, 0x61, 0xa8, 0xfc, 0x11, 0x14, 0x63, 0x91, 0x44, 0xab, 0x78, 0x22,
	0x52, 0x8d, 0x2b, 0xea, 0x72, 0x9e, 0x06, 0xf9, 0xe6, 0x98, 0x3d, 0x00, 0x88, 0xa3, 0xf9, 0xbc,
	0xb7, 0x5a, 0x8c, 0x45, 0x9c, 0x2a, 0x6a, 0x44, 0x6e, 0x5b, 0xdc, 0x5f, 0x16, 0xe4, 0xa9, 0xb8,
	0x1b, 0x6f, 0xf0, 0x18, 0xaa, 0x11, 0xd6, 0x1a, 0x9f, 0x45, 0x8b, 0x65, 0x14, 0x92, 0x19, 0xf4,
	0x2b, 0xec, 0x44, 0xd9, 0xd3, 0x3d, 0xef, 0xf0, 0x8e, 0x6a, 0x26, 0xdb, 0x73, 0x46, 0xff, 0x5b,
	0x16, 0x7d, 0x0c, 0x55, 0xf2, 0x80, 0x21, 0xe8, 0x7b, 0x90, 0x8f, 0x23, 0x7f, 0x9a, 0x8a, 0x59,
	0xd2, 0x62, 0x62, 0x80, 0xab, 0x70, 0xe3, 0x8f, 0x1c, 0xe4, 0x95, 0x6b, 0x76, 0xbb, 0xbc, 0x07,
	0x85, 0x28, 0x0e, 0x66, 0x41, 0x98, 0x76, 0x97, 0xee, 0x18, 0x83, 0xbc, 0xfc, 0x09, 0xa3, 0xb6,
	0x8a, 0xaa, 0xb5, 0xe9, 0x4a, 0x6a, 0xad, 0x9e, 0xcf, 0xba, 0x52, 0xa9, 0x88, 0xbc, 0x50, 0xfc,
	0x2c, 0x95, 0xa3, 0x90, 0x47, 0x6b, 0x8a, 0x2d, 0x63, 0xf1, 0xa6, 0x5e, 0xd0, 0x31, 0x5a, 0xb3,
	0x47, 0xe0, 0xe2, 0x4d, 0xc8, 0xf2, 0xc9, 0xa5, 0xf5, 0x22, 0x1e, 0x95, 0xb8, 0x19, 0xda, 0xd1,
	0xf5, 0xc0, 0xd0, 0x35, 0xdb, 0xfa, 0xff, 0xa9, 0xeb, 0x2f, 0x36, 0x94, 0x3a, 0x38, 0x4f, 0x4e,
	0x23, 0x1f, 0x3f, 0xe8, 0x0e, 0x54, 0x02, 0xe3, 0x53, 0x4a, 0x50, 0x36, 0x1b, 0xb3, 0xbd, 0xaf,
	0x8a, 0xd8, 0xc0, 0x32, 0x9f, 0x5b, 0xe2, 0x85, 0x32, 0xbe, 0xe6, 0x59, 0x1e, 0xce, 0x14, 0x47,
	0xa2, 0x38, 0x09, 0x6a, 0x4c, 0x09, 0xde, 0xdd, 0x49, 0x40, 0xc2, 0xa5, 0x44, 0x8d, 0x23, 0x82,
	0xc0, 0x26, 0xc9, 0x4e, 0xfb, 0x08, 0x24, 0xc0, 0x9a, 0xa0, 0x70, 0x87, 0x43, 0x60, 0x37, 0xcb,
	0x60, 0x35, 0xb0, 0x7f, 0x14, 0xd7, 0xe9, 0x6b, 0xd3, 0x92, 0x7d, 0x08, 0xce, 0x1b, 0x7f, 0xbe,
	0xd2, 0x13, 0xc5, 0x3d, 0x79, 0xfb, 0xc6, 0xbc, 0xe0, 0xfa, 0xfc, 0xf3, 0xdc, 0x67, 0xd6, 0xe1,
	0x19, 0xc0, 0xb6, 0xb4, 0x3d, 0xc9, 0x1e, 0x66, 0x93, 0x95, 0x36, 0xa6, 0xdf, 0x49, 0xb2, 0x2d,
	0xf7, 0xbf, 0x26, 0x21, 0x86, 0x91, 0xa4, 0xf1, 0x67, 0x0e, 0x2a, 0x83, 0xb9, 0x7f, 0x2d, 0xe2,
	0x41, 0x1c, 0x5d, 0x91, 0xcf, 0xbe, 0x86, 0xd2, 0x7a, 0x42, 0x64, 0xdf, 0x25, 0x03, 0xdb, 0xcc,
	0x93, 0x54, 0xad, 0x2d, 0x87, 0x7d, 0x00, 0x15, 0xf4, 0x74, 0x18, 0x84, 0xb3, 0x41, 0x84, 0xaf,
	0x95, 0xa4, 0x93, 0x25, 0x1b, 0x24, 0x9b, 0x6e, 0x47, 0x7d, 0x92, 0x4e, 0x70, 0x33, 0xc4, 0xee,
	0x82, 0x43, 0x5f, 0x58, 0xa2, 0xbe, 0x06, 0x87, 0xeb, 0xcd, 0x2d, 0x7d, 0x78, 0xf8, 0x0c, 0xaa,
	0xd9, 0xca, 0x4d, 0xe1, 0x1c, 0x2d, 0xdc, 0x5d, 0x53, 0x38, 0xc7, 0x54, 0xeb, 0x77, 0x1b, 0x8a,
	0x64, 0x96, 0x36, 0xfe, 0x2a, 0x62, 0x9f, 0xce, 0x98, 0x4c, 0xa3, 0xa8, 0xee, 0x49, 0x35, 0x6b,
	0x25, 0xae, 0x0f, 0xd9, 0xa7, 0x50, 0x5c, 0x6a, 0xc9, 0xd6, 0x26, 0xbd, 0xbf, 0x01, 0x52, 0x9a,
	0x66, 0x2a, 0x68, 0xaa, 0xe3, 0x06, 0x4c, 0xe9, 0xb1, 0x7e, 0x29, 0x94, 0x34, 0x55, 0x23, 0xfd,
	0x90, 0xa2, 0x5c, 0x1f, 0xb2, 0x6f, 0xc0, 0x55, 0x23, 0x22, 0x90, 0xd7, 0x17, 0xfe, 0x12, 0xa5,
	0xa2, 0x1b, 0x1e, 0x64, 0x6f, 0xe8, 0x6e, 0x01, 0xfa, 0x12, 0x93, 0x72, 0x5b, 0x41, 0xfb, 0xe8,
	0x1f, 0xb3, 0x83, 0x3d, 0x7a, 0x3e, 0xc9, 0x1a, 0x91, 0xdd, 0x74, 0x93, 0x69, 0xeb, 0xaf, 0xa0,
	0xb6, 0x5b, 0xf0, 0xbf, 0xbd, 0x51, 0xd9, 0xe0, 0x1f, 0xbd, 0x00, 0xd8, 0xfe, 0x9f, 0xc0, 0xbf,
	0x07, 0xc5, 0x5e, 0x7f, 0xe8, 0x8d, 0x46, 0xe7, 0x5e, 0xed, 0x2d, 0x56, 0x81, 0x12, 0xf7, 0xda,
	0xe9, 0xd6, 0x62, 0x77, 0xc0, 0xed, 0x70, 0xcf, 0xeb, 0xa5, 0x81, 0x1c, 0xce, 0x70, 0x38, 0x3d,
	0xbf, 0xf4, 0xd2, 0xbd, 0x7d, 0x34, 0x80, 0xe2, 0xda, 0x2d, 0xac, 0x08, 0xf9, 0x6f, 0xbb, 0xe7,
	0xe7, 0x98, 0x05, 0xa0, 0xf0, 0xbc, 0xcf, 0xbd, 0xe1, 0x08, 0x53, 0x60, 0xfe, 0x8b, 0xfe, 0x65,
	0x6f, 0xd4, 0xea, 0xf6, 0x90, 0x5f, 0x02, 0xe7, 0x79, 0xd7, 0x3b, 0x6f, 0xd7, 0x6c, 0xe6, 0xc2,
	0xc1, 0xa0, 0x35, 0x1c, 0x5d, 0x72, 0xaf, 0x96, 0x27, 0xee, 0x59, 0xeb, 0x62, 0x50, 0x73, 0x8e,
	0x9e, 0x41, 0x9e, 0x7e, 0x3c, 0x28, 0x47, 0xaf, 0xcf, 0xfb, 0xad, 0x36, 0xe6, 0x43, 0x28, 0x56,
	0xa5, 0x36, 0x16, 0x95, 0xa8, 0x6a, 0x52, 0xdb, 0x1c, 0xe5, 0xa7, 0x8a, 0xd4, 0xce, 0x3e, 0x7a,
	0x0c, 0x05, 0xad, 0x1b, 0x3b, 0x00, 0x1b, 0x39, 0x48, 0xc6, 0x2b, 0x15, 0x1e, 0xa9, 0x78, 0x0b,
	0x61, 0x6b, 0xb9, 0xa3, 0x5f, 0x2d, 0x3d, 0x6d, 0x95, 0x55, 0x28, 0xff, 0x8b, 0x7e, 0xb7, 0xd7,
	0xed, 0x75, 0x34, 0x9e, 0xf3, 0x3e, 0xf6, 0x61, 0x51, 0x0d, 0x7c, 0xc4, 0x5b, 0x6d, 0xea, 0x1c,
	0xb9, 0xbc, 0xed, 0x7d, 0x87, 0x85, 0x23, 0xe0, 0x54, 0x01, 0xf2, 0x04, 0x38, 0xd5, 0x00, 0x47,
	0x25, 0x27, 0x40, 0x41, 0xdf, 0x48, 0x80, 0x03, 0x02, 0x74, 0x34, 0xa0, 0x48, 0x80, 0x0e, 0x01,
	0x4a, 0x2a, 0xd7, 0xf7, 0xfd, 0x5e, 0x0d, 0x14, 0x89, 0x56, 0xae, 0x3a, 0xa5, 0x55, 0x79, 0x5c,
	0x50, 0x8e, 0x7a, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x14, 0x81, 0x61, 0x5f, 0x0a,
	0x00, 0x00,
}
