// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trxargs.proto

package tfc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildType int32

const (
	BuildType_ROAD   BuildType = 0
	BuildType_SETTLE BuildType = 1
)

var BuildType_name = map[int32]string{
	0: "ROAD",
	1: "SETTLE",
}
var BuildType_value = map[string]int32{
	"ROAD":   0,
	"SETTLE": 1,
}

func (x BuildType) String() string {
	return proto.EnumName(BuildType_name, int32(x))
}
func (BuildType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{0}
}

type BattleAction int32

const (
	BattleAction_ATTACK  BattleAction = 0
	BattleAction_DEFFEND BattleAction = 1
)

var BattleAction_name = map[int32]string{
	0: "ATTACK",
	1: "DEFFEND",
}
var BattleAction_value = map[string]int32{
	"ATTACK":  0,
	"DEFFEND": 1,
}

func (x BattleAction) String() string {
	return proto.EnumName(BattleAction_name, int32(x))
}
func (BattleAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{1}
}

type GameTrxType int32

const (
	GameTrxType_JOIN      GameTrxType = 0
	GameTrxType_NEXT      GameTrxType = 1
	GameTrxType_ROLL      GameTrxType = 2
	GameTrxType_TRADE     GameTrxType = 3
	GameTrxType_DEV       GameTrxType = 4
	GameTrxType_BATTLE    GameTrxType = 5
	GameTrxType_REGISTERL GameTrxType = 6
)

var GameTrxType_name = map[int32]string{
	0: "JOIN",
	1: "NEXT",
	2: "ROLL",
	3: "TRADE",
	4: "DEV",
	5: "BATTLE",
	6: "REGISTERL",
}
var GameTrxType_value = map[string]int32{
	"JOIN":      0,
	"NEXT":      1,
	"ROLL":      2,
	"TRADE":     3,
	"DEV":       4,
	"BATTLE":    5,
	"REGISTERL": 6,
}

func (x GameTrxType) String() string {
	return proto.EnumName(GameTrxType_name, int32(x))
}
func (GameTrxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{2}
}

type JoinTrxPayload struct {
	Player               Player   `protobuf:"varint,1,opt,name=player,proto3,enum=tfc.Player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTrxPayload) Reset()         { *m = JoinTrxPayload{} }
func (m *JoinTrxPayload) String() string { return proto.CompactTextString(m) }
func (*JoinTrxPayload) ProtoMessage()    {}
func (*JoinTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{0}
}
func (m *JoinTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTrxPayload.Unmarshal(m, b)
}
func (m *JoinTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTrxPayload.Marshal(b, m, deterministic)
}
func (dst *JoinTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTrxPayload.Merge(dst, src)
}
func (m *JoinTrxPayload) XXX_Size() int {
	return xxx_messageInfo_JoinTrxPayload.Size(m)
}
func (m *JoinTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTrxPayload proto.InternalMessageInfo

func (m *JoinTrxPayload) GetPlayer() Player {
	if m != nil {
		return m.Player
	}
	return Player_RED
}

type TradeTrxPayload struct {
	Source               Player    `protobuf:"varint,1,opt,name=source,proto3,enum=tfc.Player" json:"source,omitempty"`
	Dest                 Player    `protobuf:"varint,2,opt,name=dest,proto3,enum=tfc.Player" json:"dest,omitempty"`
	Resource             *Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount               int32     `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TradeTrxPayload) Reset()         { *m = TradeTrxPayload{} }
func (m *TradeTrxPayload) String() string { return proto.CompactTextString(m) }
func (*TradeTrxPayload) ProtoMessage()    {}
func (*TradeTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{1}
}
func (m *TradeTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeTrxPayload.Unmarshal(m, b)
}
func (m *TradeTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeTrxPayload.Marshal(b, m, deterministic)
}
func (dst *TradeTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeTrxPayload.Merge(dst, src)
}
func (m *TradeTrxPayload) XXX_Size() int {
	return xxx_messageInfo_TradeTrxPayload.Size(m)
}
func (m *TradeTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TradeTrxPayload proto.InternalMessageInfo

func (m *TradeTrxPayload) GetSource() Player {
	if m != nil {
		return m.Source
	}
	return Player_RED
}

func (m *TradeTrxPayload) GetDest() Player {
	if m != nil {
		return m.Dest
	}
	return Player_RED
}

func (m *TradeTrxPayload) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *TradeTrxPayload) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BuildRoadPayload struct {
	EdgeID               int32    `protobuf:"varint,1,opt,name=edgeID,proto3" json:"edgeID,omitempty"`
	Player               Player   `protobuf:"varint,2,opt,name=player,proto3,enum=tfc.Player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRoadPayload) Reset()         { *m = BuildRoadPayload{} }
func (m *BuildRoadPayload) String() string { return proto.CompactTextString(m) }
func (*BuildRoadPayload) ProtoMessage()    {}
func (*BuildRoadPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{2}
}
func (m *BuildRoadPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRoadPayload.Unmarshal(m, b)
}
func (m *BuildRoadPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRoadPayload.Marshal(b, m, deterministic)
}
func (dst *BuildRoadPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRoadPayload.Merge(dst, src)
}
func (m *BuildRoadPayload) XXX_Size() int {
	return xxx_messageInfo_BuildRoadPayload.Size(m)
}
func (m *BuildRoadPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRoadPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRoadPayload proto.InternalMessageInfo

func (m *BuildRoadPayload) GetEdgeID() int32 {
	if m != nil {
		return m.EdgeID
	}
	return 0
}

func (m *BuildRoadPayload) GetPlayer() Player {
	if m != nil {
		return m.Player
	}
	return Player_RED
}

type BuildSettlePayload struct {
	SettleID             int32    `protobuf:"varint,1,opt,name=settleID,proto3" json:"settleID,omitempty"`
	Player               Player   `protobuf:"varint,2,opt,name=player,proto3,enum=tfc.Player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildSettlePayload) Reset()         { *m = BuildSettlePayload{} }
func (m *BuildSettlePayload) String() string { return proto.CompactTextString(m) }
func (*BuildSettlePayload) ProtoMessage()    {}
func (*BuildSettlePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{3}
}
func (m *BuildSettlePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildSettlePayload.Unmarshal(m, b)
}
func (m *BuildSettlePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildSettlePayload.Marshal(b, m, deterministic)
}
func (dst *BuildSettlePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildSettlePayload.Merge(dst, src)
}
func (m *BuildSettlePayload) XXX_Size() int {
	return xxx_messageInfo_BuildSettlePayload.Size(m)
}
func (m *BuildSettlePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildSettlePayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildSettlePayload proto.InternalMessageInfo

func (m *BuildSettlePayload) GetSettleID() int32 {
	if m != nil {
		return m.SettleID
	}
	return 0
}

func (m *BuildSettlePayload) GetPlayer() Player {
	if m != nil {
		return m.Player
	}
	return Player_RED
}

type BuildTrxPayload struct {
	Type                 BuildType           `protobuf:"varint,1,opt,name=type,proto3,enum=tfc.BuildType" json:"type,omitempty"`
	BuildRoadPayload     *BuildRoadPayload   `protobuf:"bytes,2,opt,name=buildRoadPayload,proto3" json:"buildRoadPayload,omitempty"`
	BuildSettlePayload   *BuildSettlePayload `protobuf:"bytes,3,opt,name=buildSettlePayload,proto3" json:"buildSettlePayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BuildTrxPayload) Reset()         { *m = BuildTrxPayload{} }
func (m *BuildTrxPayload) String() string { return proto.CompactTextString(m) }
func (*BuildTrxPayload) ProtoMessage()    {}
func (*BuildTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{4}
}
func (m *BuildTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTrxPayload.Unmarshal(m, b)
}
func (m *BuildTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTrxPayload.Marshal(b, m, deterministic)
}
func (dst *BuildTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTrxPayload.Merge(dst, src)
}
func (m *BuildTrxPayload) XXX_Size() int {
	return xxx_messageInfo_BuildTrxPayload.Size(m)
}
func (m *BuildTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTrxPayload proto.InternalMessageInfo

func (m *BuildTrxPayload) GetType() BuildType {
	if m != nil {
		return m.Type
	}
	return BuildType_ROAD
}

func (m *BuildTrxPayload) GetBuildRoadPayload() *BuildRoadPayload {
	if m != nil {
		return m.BuildRoadPayload
	}
	return nil
}

func (m *BuildTrxPayload) GetBuildSettlePayload() *BuildSettlePayload {
	if m != nil {
		return m.BuildSettlePayload
	}
	return nil
}

type BattleTrxPayload struct {
	Action               BattleAction `protobuf:"varint,1,opt,name=action,proto3,enum=tfc.BattleAction" json:"action,omitempty"`
	NOfUnits             int32        `protobuf:"varint,2,opt,name=nOfUnits,proto3" json:"nOfUnits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BattleTrxPayload) Reset()         { *m = BattleTrxPayload{} }
func (m *BattleTrxPayload) String() string { return proto.CompactTextString(m) }
func (*BattleTrxPayload) ProtoMessage()    {}
func (*BattleTrxPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{5}
}
func (m *BattleTrxPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleTrxPayload.Unmarshal(m, b)
}
func (m *BattleTrxPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleTrxPayload.Marshal(b, m, deterministic)
}
func (dst *BattleTrxPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleTrxPayload.Merge(dst, src)
}
func (m *BattleTrxPayload) XXX_Size() int {
	return xxx_messageInfo_BattleTrxPayload.Size(m)
}
func (m *BattleTrxPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleTrxPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BattleTrxPayload proto.InternalMessageInfo

func (m *BattleTrxPayload) GetAction() BattleAction {
	if m != nil {
		return m.Action
	}
	return BattleAction_ATTACK
}

func (m *BattleTrxPayload) GetNOfUnits() int32 {
	if m != nil {
		return m.NOfUnits
	}
	return 0
}

type TrxArgs struct {
	Type                 GameTrxType       `protobuf:"varint,1,opt,name=type,proto3,enum=tfc.GameTrxType" json:"type,omitempty"`
	TradeTrxPayload      *TradeTrxPayload  `protobuf:"bytes,2,opt,name=tradeTrxPayload,proto3" json:"tradeTrxPayload,omitempty"`
	BuildTrxPayload      *BuildTrxPayload  `protobuf:"bytes,3,opt,name=buildTrxPayload,proto3" json:"buildTrxPayload,omitempty"`
	BattleTrxPayload     *BattleTrxPayload `protobuf:"bytes,4,opt,name=battleTrxPayload,proto3" json:"battleTrxPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrxArgs) Reset()         { *m = TrxArgs{} }
func (m *TrxArgs) String() string { return proto.CompactTextString(m) }
func (*TrxArgs) ProtoMessage()    {}
func (*TrxArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_trxargs_c29e33cebad126ba, []int{6}
}
func (m *TrxArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrxArgs.Unmarshal(m, b)
}
func (m *TrxArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrxArgs.Marshal(b, m, deterministic)
}
func (dst *TrxArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrxArgs.Merge(dst, src)
}
func (m *TrxArgs) XXX_Size() int {
	return xxx_messageInfo_TrxArgs.Size(m)
}
func (m *TrxArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_TrxArgs.DiscardUnknown(m)
}

var xxx_messageInfo_TrxArgs proto.InternalMessageInfo

func (m *TrxArgs) GetType() GameTrxType {
	if m != nil {
		return m.Type
	}
	return GameTrxType_JOIN
}

func (m *TrxArgs) GetTradeTrxPayload() *TradeTrxPayload {
	if m != nil {
		return m.TradeTrxPayload
	}
	return nil
}

func (m *TrxArgs) GetBuildTrxPayload() *BuildTrxPayload {
	if m != nil {
		return m.BuildTrxPayload
	}
	return nil
}

func (m *TrxArgs) GetBattleTrxPayload() *BattleTrxPayload {
	if m != nil {
		return m.BattleTrxPayload
	}
	return nil
}

func init() {
	proto.RegisterType((*JoinTrxPayload)(nil), "tfc.JoinTrxPayload")
	proto.RegisterType((*TradeTrxPayload)(nil), "tfc.TradeTrxPayload")
	proto.RegisterType((*BuildRoadPayload)(nil), "tfc.BuildRoadPayload")
	proto.RegisterType((*BuildSettlePayload)(nil), "tfc.BuildSettlePayload")
	proto.RegisterType((*BuildTrxPayload)(nil), "tfc.BuildTrxPayload")
	proto.RegisterType((*BattleTrxPayload)(nil), "tfc.BattleTrxPayload")
	proto.RegisterType((*TrxArgs)(nil), "tfc.TrxArgs")
	proto.RegisterEnum("tfc.BuildType", BuildType_name, BuildType_value)
	proto.RegisterEnum("tfc.BattleAction", BattleAction_name, BattleAction_value)
	proto.RegisterEnum("tfc.GameTrxType", GameTrxType_name, GameTrxType_value)
}

func init() { proto.RegisterFile("trxargs.proto", fileDescriptor_trxargs_c29e33cebad126ba) }

var fileDescriptor_trxargs_c29e33cebad126ba = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xb6, 0x50, 0x0a, 0x9c, 0x0a, 0x3b, 0x4e, 0x56, 0x25, 0x7b, 0xa3, 0x56, 0x13, 0xdd, 0xbd,
	0xe0, 0x02, 0xe3, 0xad, 0x49, 0xd7, 0x76, 0x09, 0x2b, 0x81, 0xcd, 0xd0, 0x35, 0xea, 0xdd, 0x40,
	0x67, 0x09, 0x09, 0xdb, 0x92, 0x76, 0x48, 0x96, 0x57, 0xf1, 0x6d, 0x7c, 0x25, 0x9f, 0xc0, 0xe9,
	0x69, 0xe9, 0xb6, 0x05, 0x13, 0xef, 0x3a, 0xe7, 0xfb, 0x99, 0x39, 0xdf, 0x39, 0x29, 0x74, 0x64,
	0xf4, 0xc0, 0xa3, 0x65, 0xdc, 0xdf, 0x44, 0xa1, 0x0c, 0x69, 0x5d, 0xde, 0x2d, 0xce, 0xba, 0x4b,
	0x7e, 0x2f, 0x7c, 0x2e, 0x79, 0x5a, 0xb4, 0x3e, 0x41, 0xf7, 0x3a, 0x5c, 0x05, 0x5e, 0xf4, 0x70,
	0xc3, 0x77, 0xeb, 0x90, 0xfb, 0xf4, 0x2d, 0x18, 0x9b, 0x35, 0xdf, 0x89, 0xa8, 0xa7, 0xbd, 0xd6,
	0x3e, 0x74, 0x07, 0x66, 0x5f, 0xe9, 0xfa, 0x37, 0x58, 0x62, 0x19, 0x64, 0xfd, 0xd2, 0xe0, 0xc4,
	0x8b, 0xb8, 0x2f, 0xca, 0xc2, 0x38, 0xdc, 0x46, 0x0b, 0x71, 0x54, 0x98, 0x42, 0xf4, 0x15, 0xe8,
	0xbe, 0x88, 0x65, 0xaf, 0x76, 0x48, 0x41, 0x80, 0x9e, 0x43, 0x2b, 0x12, 0x99, 0x4f, 0x5d, 0x91,
	0xcc, 0x41, 0x07, 0x49, 0x2c, 0x2b, 0xb2, 0x1c, 0xa6, 0x2f, 0xc0, 0xe0, 0xf7, 0xe1, 0x36, 0x90,
	0x3d, 0x5d, 0x11, 0x1b, 0x2c, 0x3b, 0x59, 0x53, 0x20, 0x97, 0xdb, 0xd5, 0xda, 0x67, 0xea, 0x55,
	0xfb, 0xc7, 0x29, 0xae, 0xf0, 0x97, 0x62, 0xe4, 0xe0, 0xe3, 0x14, 0x37, 0x3d, 0x15, 0xba, 0xad,
	0xfd, 0xbb, 0xdb, 0x5b, 0xa0, 0x68, 0x38, 0x13, 0x52, 0xae, 0xc5, 0xde, 0xf2, 0x0c, 0x5a, 0x31,
	0x16, 0x72, 0xd3, 0xfc, 0xfc, 0x7f, 0xb6, 0xbf, 0x55, 0x88, 0xe8, 0x5b, 0x08, 0xd1, 0x02, 0x5d,
	0xee, 0x36, 0xfb, 0x08, 0xbb, 0x28, 0x4b, 0x39, 0xaa, 0xca, 0x10, 0xa3, 0x36, 0x90, 0x79, 0xa5,
	0x3f, 0xbc, 0xc6, 0x1c, 0x3c, 0x7f, 0xe4, 0x17, 0x40, 0x76, 0x40, 0xa7, 0x43, 0xa0, 0xf3, 0x83,
	0x8e, 0xb2, 0xbc, 0x5f, 0x3e, 0x9a, 0x94, 0x60, 0x76, 0x44, 0x62, 0xfd, 0x50, 0x59, 0xf3, 0xa4,
	0x50, 0xe8, 0xe1, 0x5c, 0xcd, 0x65, 0x21, 0x57, 0x61, 0x90, 0x75, 0xf1, 0x2c, 0x35, 0x44, 0x9a,
	0x8d, 0x00, 0xcb, 0x08, 0x49, 0x86, 0xc1, 0xf4, 0xee, 0x36, 0x58, 0xc9, 0x18, 0x5b, 0x50, 0x19,
	0xee, 0xcf, 0xd6, 0x1f, 0x0d, 0x9a, 0xca, 0xd5, 0x56, 0x1b, 0x4c, 0xdf, 0x95, 0x62, 0x21, 0x68,
	0x38, 0x54, 0x9b, 0xac, 0xf0, 0x42, 0x30, 0x9f, 0xe1, 0x44, 0x96, 0x97, 0x32, 0xcb, 0xe5, 0x14,
	0x05, 0x95, 0x85, 0x65, 0x55, 0x72, 0xa2, 0x9f, 0x97, 0xe7, 0x91, 0x45, 0x72, 0x5a, 0x98, 0x43,
	0x41, 0x5f, 0x21, 0xe3, 0x60, 0x2a, 0x61, 0xe0, 0x6a, 0xe6, 0x83, 0xa9, 0x80, 0xec, 0x80, 0x7e,
	0xf1, 0x06, 0xda, 0xf9, 0xb8, 0x69, 0x0b, 0x74, 0x36, 0xb5, 0x1d, 0xf2, 0x84, 0x02, 0x18, 0x33,
	0xd7, 0xf3, 0xc6, 0x2e, 0xd1, 0x2e, 0xde, 0xc3, 0xd3, 0x62, 0x96, 0x09, 0x66, 0x7b, 0x9e, 0xfd,
	0xe5, 0xab, 0xe2, 0x99, 0xd0, 0x74, 0xdc, 0xab, 0x2b, 0x77, 0xe2, 0x28, 0xe2, 0x4f, 0x30, 0x0b,
	0x19, 0x25, 0x6e, 0xd7, 0xd3, 0xd1, 0x44, 0xb1, 0xd4, 0xd7, 0xc4, 0xfd, 0xee, 0x11, 0x2d, 0xbd,
	0x61, 0x3c, 0x26, 0x35, 0xda, 0x86, 0x86, 0xc7, 0x6c, 0xc7, 0x25, 0x75, 0xda, 0x84, 0xba, 0xe3,
	0x7e, 0x23, 0x7a, 0xe2, 0x7c, 0x69, 0xe3, 0xad, 0x0d, 0xda, 0x81, 0x36, 0x73, 0x87, 0xa3, 0x99,
	0xe7, 0xb2, 0x31, 0x31, 0xe6, 0x06, 0xfe, 0x3e, 0x3e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0x50, 0x89, 0xbb, 0x64, 0x04, 0x00, 0x00,
}
